### ISSUE TITLE
Can't start hy on Windows

### ISSUE THREAD

**Issue by krysros** [hylang/hy#1022]
Can't start hy REPL on Windows. Command-line output below:

    C:\Users\Kros\Desktop>py -m venv testhy

    C:\Users\Kros\Desktop>testhy\Scripts\activate.bat
    (testhy) C:\Users\Kros\Desktop>python -m pip install -U pip
    Collecting pip
      Using cached pip-8.0.2-py2.py3-none-any.whl
    Installing collected packages: pip
      Found existing installation: pip 7.1.2
        Uninstalling pip-7.1.2:
          Successfully uninstalled pip-7.1.2
    Successfully installed pip-8.0.2

    (testhy) C:\Users\Kros\Desktop>pip install hy
    Collecting hy
      Using cached hy-0.11.1.tar.gz
    Collecting rply>=0.7.0 (from hy)
      Using cached rply-0.7.4-py2.py3-none-any.whl
    Collecting astor>=0.5 (from hy)
      Using cached astor-0.5-py2.py3-none-any.whl
    Collecting clint>=0.4 (from hy)
      Using cached clint-0.5.1.tar.gz
    Collecting pyreadline==2.0 (from hy)
      Using cached pyreadline-2.0.zip
    Collecting appdirs (from rply>=0.7.0->hy)
      Using cached appdirs-1.4.0-py2.py3-none-any.whl
    Collecting args (from clint>=0.4->hy)
      Using cached args-0.1.0.tar.gz
    Installing collected packages: appdirs, rply, astor, args, clint, pyreadline, hy
      Running setup.py install for args ... done
      Running setup.py install for clint ... done
      Running setup.py install for pyreadline ... done
      Running setup.py install for hy ... done
    Successfully installed appdirs-1.4.0 args-0.1.0 astor-0.5 clint-0.5.1 hy-0.11.1 pyreadline-2.0 rply-0.7.4

    (testhy) C:\Users\Kros\Desktop>hy
    Traceback (most recent call last):
      File "C:\Users\Kros\Desktop\testhy\Scripts\hy-script.py", line 9, in <module>
        load_entry_point('hy==0.11.1', 'console_scripts', 'hy')()
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
        return ep.load()
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
        return self.resolve()
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "c:\users\kros\desktop\testhy\lib\site-packages\hy\cmdline.py", line 44, in <module>
        from hy.completer import completion
      File "c:\users\kros\desktop\testhy\lib\site-packages\hy\completer.py", line 41, in <module>
        import readline
      File "c:\users\kros\desktop\testhy\lib\site-packages\readline.py", line 6, in <module>
        from pyreadline.rlmain import Readline
      File "c:\users\kros\desktop\testhy\lib\site-packages\pyreadline\__init__.py", line 11, in <module>
        from . import unicode_helper, logger, clipboard, lineeditor, modes, console
      File "c:\users\kros\desktop\testhy\lib\site-packages\pyreadline\console\__init__.py", line 15, in <module>
        from .console import *
      File "c:\users\kros\desktop\testhy\lib\site-packages\pyreadline\console\console.py", line 610, in <module>
        msvcrt = cdll.LoadLibrary(ctypes.util.find_msvcrt())
      File "C:\Users\Kros\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 425, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\Kros\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 347, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: bad argument type for built-in operation

    (testhy) C:\Users\Kros\Desktop>

Python 3.5.1 (32-bit) on Windows 10.

**Comment by rwtolbert** [comment]
Try this:

 pip install pyreadline==2.1

Python 3.5 needs an update to the latest pyreadline. Thy Hy requirements haven't quite caught up.

**Comment by krysros** [comment]
@rwtolbert 

Thanks for your reply. After updating `pyreadline`:

    (testhy) C:\Users\Kros\Desktop>pip install pyreadline==2.1
    Collecting pyreadline==2.1
      Using cached pyreadline-2.1.zip
    Installing collected packages: pyreadline
      Found existing installation: pyreadline 2.0
        Uninstalling pyreadline-2.0:
          Successfully uninstalled pyreadline-2.0
      Running setup.py install for pyreadline ... done
    Successfully installed pyreadline-2.1

    (testhy) C:\Users\Kros\Desktop>hy
    Traceback (most recent call last):
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 651, in _build_master
        ws.require(__requires__)
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 952, in require
        needed = self.resolve(parse_requirements(requirements))
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 844, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (pyreadline 2.1 (c:\users\kros\desktop\testhy\lib\site-packages), Requirement.parse('pyreadline==2.0'), {'hy'})

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Kros\Desktop\testhy\Scripts\hy-script.py", line 5, in <module>
        from pkg_resources import load_entry_point
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 3084, in <module>
        @_call_aside
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 3070, in _call_aside
        f(*args, **kwargs)
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 3097, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 653, in _build_master
        return cls._build_from_requirements(__requires__)
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "c:\users\kros\desktop\testhy\lib\site-packages\pkg_resources\__init__.py", line 839, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pyreadline==2.0' distribution was not found and is required by hy

**Comment by zackmdavis** [comment]
@krysros thanks for the bug report. This should be fixed on master as of a few minutes ago (#1011). There's no PyPI release yet, but you should be able to install master from GitHub with `pip install git+git://github.com/hylang/hy.git`. (And reopen this Issue if it doesn't work!)
