### ISSUE TITLE
quasiquote not working

### ISSUE THREAD

**Issue by ez47** [hylang/hy#1025]
```$ hy index.hy```
```
(defn deftype [wat, &rest args]
    `("Type" ~wat ~@args)
)
(print (deftype "string" "asdadasd"))
```

```
Traceback (most recent call last):
  File "/bin/hy", line 9, in <module>
    load_entry_point('hy==0.11.1', 'console_scripts', 'hy')()
  File "/local/lib/python2.7/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/local/lib/python2.7/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/local/lib/python2.7/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/local/lib/python2.7/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "index.hy", line 5, in <module>
    (print (deftype "string" "asdadasd"))
  File "index.hy", line 2, in deftype
    `("Type" ~wat ~@args)
NameError: global name 'wat' is not defined
```

**Comment by paultag** [comment]
You have a typo, the function defines a var `wat,`

**Comment by paultag** [comment]
```
[paultag@cassiel:~][⌚ 09:51 PM] ♥  cat test.hy 
(defn deftype [wat &rest args]
    `("Type" ~wat ~@args))

(print (deftype "string" "asdadasd"))
[paultag@cassiel:~][⌚ 09:51 PM] ♥  hy test.hy 
('Type' 'string' 'asdadasd')
```

Closing! Thanks for the bug! :D

**Comment by ez47** [comment]
oh yea. i see clsing

**Comment by algernon** [comment]
FWIW, [hylang/hydiomatic](https://github.com/hylang/hydiomatic/blob/5d3c95887a76b9502865118e30deb8dbab4d953c/tests/hydiomatic_tests.hy#L302-L306) can catch these kind of issues. :)
