### ISSUE TITLE
eval can only see locals

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1041]
Eval works on symbols for modules:

``` Python
=> (import operator)
import operator
=> (eval 'operator)
from hy.importer import hy_eval
from hy import HySymbol
hy_eval(HySymbol('operator'), locals(), '__console__')
<module 'operator' from 'C:\\Python34\\Scripts\\env-hy\\lib\\operator.py'>
```

Functions can return modules:

``` Python
=> ((fn [] operator))
def _hy_anon_fn_1():
    return operator
_hy_anon_fn_1()
<module 'operator' from 'C:\\Python34\\Scripts\\env-hy\\lib\\operator.py'>
```

Functions can return the result of an eval:

``` Python
=> ((fn [] (eval 'first)))
from hy.importer import hy_eval
from hy import HySymbol

def _hy_anon_fn_1():
    return hy_eval(HySymbol('first'), locals(), '__console__')
_hy_anon_fn_1()
<function first at 0x000000000369DC80>
```

But not if it's a module!

``` Python
=> ((fn [] (eval 'operator)))
from hy.importer import hy_eval
from hy import HySymbol

def _hy_anon_fn_1():
    return hy_eval(HySymbol('operator'), locals(), '__console__')
_hy_anon_fn_1()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in _hy_anon_fn_1
  File "c:\users\me\code\repos\hy\hy\importer.py", line 134, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'operator' is not defined
```

I am surprised by this. Are you?

**Comment by gilch** [comment]
It's not just modules. I found a simpler illustration:
```Python
=> (def spam 42)
spam = 42
=> (eval 'spam)
from hy.importer import hy_eval
from hy import HySymbol
hy_eval(HySymbol('spam'), locals(), '__console__')
42
=> ((fn [] (eval 'spam)))
from hy.importer import hy_eval
from hy import HySymbol

def _hy_anon_fn_1():
    return hy_eval(HySymbol('spam'), locals(), '__console__')
_hy_anon_fn_1()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in _hy_anon_fn_1
  File "c:\users\me\code\repos\hy\hy\importer.py", line 134, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'spam' is not defined
=> ((fn [] (eval 'spam (globals))))
from hy.importer import hy_eval
from hy import HySymbol

def _hy_anon_fn_1():
    return hy_eval(HySymbol('spam'), globals(), '__console__')
_hy_anon_fn_1()
42
```
The equivalent Clojure works:
```Clojure
user=> (def spam 42)
#'user/spam
user=> (eval 'spam)
42
user=> ((fn [] (eval 'spam)))
42
user=>
```

**Comment by kirbyfan64** [comment]
Have a fix in the works; just writing the tests.

**Comment by allison-casey** [comment]
I don't know how yet, but this looks to be fixed.

**Comment by Kodiologist** [comment]
Don't feel like you have to find the change that fixed it. The important thing is just ensuring it's fixed.
