### ISSUE TITLE
Bad bug using macro

### ISSUE THREAD

**Issue by IndieRobert** [hylang/hy#1078]
Please hy2py the following code and notice the until loop condition is wrong:

; main
(def f False)
(def t True)

(def key (Key))
(def mouse (Mouse))

(def ESC KEY_ESCAPE)

(defmacro awhen [x &rest body]
  `(let [it ~x]
    (when it
      ~@body)))

(defmacro when1 [x &rest body]
  `(awhen ~x
     ~@body
     it))

(defmacro until [c &rest body]
  `(while (not ~c)
      ~@body))

(defmacro key? [k &rest body]
  `(when1 (console_is_key_pressed ~k)
      ~@body))

(def win_closed? console_is_window_closed)

(defn inputs []
  (sys_check_for_event EVENT_ANY key mouse))

(until (or (win_closed?) (key? ESC))
  (inputs)
  (console_flush))

**Comment by IndieRobert** [comment]
Get the following python code:
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\vrac\balanced>hy
hy 0.11.1 using CPython(default) 2.7.10 on Windows
=> (= None f)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'f' is not defined
=> (= None False)
False
=> (= None True)
False
=> None
=> (when None True)
=> (when (not None) False)
False
=> (unless None False)
False
=> (= True True)
True
=> (= 1 True)
True
=> (= 1 False)
False
=> (= 1 False)
Traceback (most recent call last):
  File "C:\Python27\Scripts\hy-script.py", line 9, in <module>
    load_entry_point('hy==0.11.1', 'console_scripts', 'hy')()
  File "c:\python27\lib\site-packages\hy\cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "c:\python27\lib\site-packages\hy\cmdline.py", line 342, in cmdline_handler
    return run_repl(spy=options.spy)
  File "c:\python27\lib\site-packages\hy\cmdline.py", line 240, in run_repl
    os=platform.system()
  File "C:\Python27\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "c:\python27\lib\site-packages\hy\completer.py", line 153, in completion
    readline.write_history_file(history)
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 169, in write_history_file
    self.mode._history.write_history_file(filename)
  File "c:\python27\lib\site-packages\pyreadline\lineeditor\history.py", line 92, in write_history_file
    fp = open(filename, 'wb')
KeyboardInterrupt

D:\vrac\balanced>

D:\vrac\balanced>hy2py main.hy
from libtcodpy import *
from misc import *
print(u'Starting up...')
console_init_root(55L, 50L, u'balanced', f)

def is_quit():

    def _hy_anon_fn_1():
        it = None
        console_is_key_pressed = ESC
        print(it)
        return (it if it else None)
    return (is_win_closed() or _hy_anon_fn_1())
while (not is_quit()):
    inputs()
    console_flush()

D:\vrac\balanced>hy2py bug.hy
import hy
from hy import HyExpression, HyList, HySymbol
f = False
t = True
key = Key()
mouse = Mouse()
ESC = KEY_ESCAPE

@hy.macros.macro(u'awhen')
def _hy_anon_fn_1(x, *body):
    return HyExpression(((([] + [HySymbol(u'let')]) + [HyList((([] + [HySymbol(u'it')]) + [x]))]) + [HyExpression(((([] + [HySymbol(u'when')]) + [HySym
bol(u'it')]) + list(body)))]))

@hy.macros.macro(u'when1')
def _hy_anon_fn_2(x, *body):
    return HyExpression((((([] + [HySymbol(u'awhen')]) + [x]) + list(body)) + [HySymbol(u'it')]))

@hy.macros.macro(u'until')
def _hy_anon_fn_3(c, *body):
    return HyExpression(((([] + [HySymbol(u'while')]) + [HyExpression((([] + [HySymbol(u'not')]) + [c]))]) + list(body)))

@hy.macros.macro(u'is_key')
def _hy_anon_fn_4(k, *body):
    return HyExpression(((([] + [HySymbol(u'when1')]) + [HyExpression((([] + [HySymbol(u'console_is_key_pressed')]) + [k]))]) + list(body)))
is_win_closed = console_is_window_closed

def inputs():
    return sys_check_for_event(EVENT_ANY, key, mouse)

def _hy_anon_fn_6():
    it = None
    console_is_key_pressed = ESC
    return (it if it else None)
while (not (is_win_closed() or _hy_anon_fn_6())):
    inputs()
    console_flush()

Notice that _hy_anon_fn_6 is completely weird

**Comment by IndieRobert** [comment]
It works with the latest. Sorry for that.
