### ISSUE TITLE
Problems running Hy interpreter

### ISSUE THREAD

**Issue by alton-campbell** [hylang/hy#1088]
I tried to run hy from the console and this happened:  
```
(C:\Anaconda3\envs\sandbox) C:\Users\User\Documents>hy
    Traceback (most recent call last):
    File "c:\anaconda3\envs\sandbox\lib\runpy.py", line 184, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\anaconda3\envs\sandbox\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\Anaconda3\envs\sandbox\Scripts\hy.exe\__main__.py", line 5, in <module>
    File "c:\anaconda3\envs\sandbox\lib\site-packages\hy\cmdline.py", line 44, in <module>
      from hy.completer import completion
    File "c:\anaconda3\envs\sandbox\lib\site-packages\hy\completer.py", line 41, in <module>
      import readline
    File "c:\anaconda3\envs\sandbox\lib\site-packages\readline.py", line 6, in <module>
      from pyreadline.rlmain import Readline
    File "c:\anaconda3\envs\sandbox\lib\site-packages\pyreadline\__init__.py", line 11, in <module>
      from . import unicode_helper, logger, clipboard, lineeditor, modes, console
    File "c:\anaconda3\envs\sandbox\lib\site-packages\pyreadline\console\__init__.py", line 15, in <module>
      from .console import *
    File "c:\anaconda3\envs\sandbox\lib\site-packages\pyreadline\console\console.py", line 610, in <module>
      msvcrt = cdll.LoadLibrary(ctypes.util.find_msvcrt())
    File "c:\anaconda3\envs\sandbox\lib\ctypes\__init__.py", line 425, in LoadLibrary
      return self._dlltype(name)
    File "c:\anaconda3\envs\sandbox\lib\ctypes\__init__.py", line 347, in __init__
      self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```
I am running Python 3.5.2 in Anaconda on Windows 10. By using hy-kernel with jupyter, I can still use Hy in a notebook.

Is there something I am missing?

**Comment by alton-campbell** [comment]
Never mind, this is a duplicate of #1022.
