### ISSUE TITLE
Hy sets are really broken.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1120]
```Hy
(env-hy) C:\Users\ME\Code>hy
hy 0.11.0 using CPython(v3.4.3:9b73f1c3e601) 3.4.3 on Windows
=> #{:a 'a}
Traceback (most recent call last):
  File "C:\Python34\Scripts\env-hy\Scripts\hy-script.py", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy')()
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\cmdline.py", line 341, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\cmdline.py", line 336, in cmdline_handler
    return run_repl(spy=options.spy)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\cmdline.py", line 234, in run_repl
    os=platform.system()
  File "C:\Python34\Lib\code.py", line 234, in interact
    more = self.push(line)
  File "C:\Python34\Lib\code.py", line 256, in push
    more = self.runsource(source, self.filename)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\cmdline.py", line 93, in runsource
    tokens = tokenize(source)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\lex\__init__.py", line 33, in tokenize
    return parser.parse(lexer.lex(buf))
  File "C:\Python34\Scripts\env-hy\lib\site-packages\rply\parser.py", line 23, in parse
    t, symstack, statestack, state
  File "C:\Python34\Scripts\env-hy\lib\site-packages\rply\parser.py", line 80, in _reduce_production
    value = p.func(targ)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\lex\parser.py", line 69, in wrapped
    ret = fun(p)
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\lex\parser.py", line 214, in t_set
    return HySet(p[1])
  File "C:\Python34\Scripts\env-hy\lib\site-packages\hy\models\set.py", line 31, in __init__
    items = sorted(items)
TypeError: unorderable types: HyExpression() < HyKeyword()

(env-hy) C:\Users\ME\Code>
```
That is NOT supposed to happen.

**Comment by kirbyfan64** [comment]
Wow, I must've been delusional when I wrote that code. Sets have nothing to do with lists, yet I had the latter derive from the former...

So you basically end up with sets. That can have duplicates appended. Out of order. And can be indexed. Ugh...

**Comment by Kodiologist** [comment]
As I understand, HySet is supposed to represent *set literals*, not sets themselves. So having duplicates, having a fixed order, and deriving from HyList is fine. HyDict does the same thing.
