### ISSUE TITLE
Import has a LOT of corner cases

### ISSUE THREAD

**Issue by refi64** [hylang/hy#1144]
```
ryan@DevPC-LX /media/ryan/stuff/hy attrerr $ ./run --spy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (import [xyz])  ; Looks ok.
import xyz
=> (import [xyz []]) ; This makes no sense and compiles as something that makes less sense.
from xyz import xyz
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name xyz
=> (import [xyz [* *]])  ; Yay stars!
from xyz import *, *
=> (import [xyz [* * * * * * * * * * * * * * * * * * * *]])  ; LOOK, it's July 4th!
from xyz import *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *
=> (import [xyz [* :as 1]])  ; I have no clue what the hell is doing.
from xyz import * as 1
=> (import [xyz [1]])  ; Speaking of which, we can import numbers (!).
from xyz import 1
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 1
=> (import [xyz [:foo]])  ; This also makes no sense.
from xyz import hy_:foo_9x8x
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name hy_:foo_9x8x
=> (import [xyz [a : b]])  ; Same as [a :as b].
from xyz import a as b
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name a
=> (import [xyz [a :RANDOM_STUFF b]])  ; Ditto.
from xyz import a as b
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name a
=> (import [xyz [a.b]])  ; Again, makes no sense.
from xyz import a.b
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name a.b
=> (import [xyz [1/2]])  ; Well, that's awkward
from xyz import (u'fraction' 1L 2L)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name (u'fraction' 1L 2L)
=> 
ryan@DevPC-LX /media/ryan/stuff/hy attrerr $ 
```

**Comment by Kodiologist** [comment]
All of these are now syntax errors, even `(import [xyz])`, which should be written `(import xyz)` instead.
