### ISSUE TITLE
Test fails on second run due to bad/incorrect/corrupt/? .pyc files 

### ISSUE THREAD

**Issue by rwtolbert** [hylang/hy#1183]
This is plain weird. 

We are creating compiled Python in a .pyc file that is different that what we run when it is created (I think)

Create a new virtualenv or conda env with Python 3. The first time the tests are run, they all pass. Run again, one fails. Remove all the .pyc files and try again, they pass.

Ok, lets try Python 3.4 on Ubuntu 14.04
```
$ pip install -e .
$ make test  # they all pass
$ make test
-- snip --
ERROR: NATIVE: testing anaphoric if
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.4/unittest/case.py", line 625, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.4/unittest/case.py", line 585, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/lib/python3.4/unittest/case.py", line 516, in _feedErrorsToResult
    result.addFailure(test, exc_info)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/proxy.py", line 143, in addFailure
    formatted = plugins.formatFailure(self.test, err)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/plugins/manager.py", line 141, in chain
    result = meth(*arg, **kw)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/plugins/failuredetail.py", line 45, in formatFailure
    tbinfo = force_unicode(inspect_traceback(tb))
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/inspector.py", line 31, in inspect_traceback
    lines, exc_line = tbsource(tb)
  File "/home/bob/.virtualenvs/hy-dev/lib/python3.4/site-packages/nose/inspector.py", line 101, in tbsource
    while lines[index-1].strip().endswith('\\'):
IndexError: list index out of range
-- snip -- 
$ find . -name "*.pyc" -delete
$ make test  # they all pass
$ make test  # anaphoric-if fails again
```

???

that said, I'm not sure what this test is even doing. Why is there a real `assert False`? 

```hy
; from tests/native-tests/anaphoric.hy

(defn test-ap-if []
  "NATIVE: testing anaphoric if"
  (ap-if True (assert-true it))
  (ap-if False True (assert-false it))
  (try (macroexpand '(ap-if True))
       (except [HyMacroExpansionError] True)
       (else (assert False))))
```

**Comment by kirbyfan64** [comment]
What do you get if you run [this](https://gist.github.com/delimitry/bad5496b52161449f6de) script on the `.pyc` files.

**Comment by rwtolbert** [comment]
```
> python compiled_file_python_version.py tests\native_tests\contrib\__pycache__\anaphoric.cpython-35.pyc
File "tests\native_tests\contrib\__pycache__\anaphoric.cpython-35.pyc" is compiled with: Python 3.5b2
```

So it is the same Python that I am using.

Not sure what this tests/proves.

**Comment by rwtolbert** [comment]
Although I have no idea why, it appears that this behavior might be related to the changes introduced in #1085. 

if i revert to 21f9589, this problem of a test failing the second time it is run disappears.

I have no idea what we modernized in the importer, but it appears to have side effects we were not prepared for.

**Comment by kirbyfan64** [comment]
For some reason I feel like this has something to do with the new `polyloader` code...

**Comment by rwtolbert** [comment]
There is clearly something broken with the new import mechanism and using "hy -m".

For some reason, using that tries to import all kind of crazy modules other than the one you ask for. Maybe I don't understand the purpose of the import modernization.

For example, even trying to run a module that doesn't exist crashes:

```
$ python -m foo.bar
/home/bob/anaconda3/envs/hy-conda/bin/python: Error while finding spec for 'foo.bar' (ImportError: No module named 'foo')
$ hy -m foo.bar
/home/bob/anaconda3/envs/hy-conda/lib/python3.5/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
[1]    798 abort (core dumped)  hy -m foo.bar
```

The fact that `python -m` doesn't throw this IPython.kernel warning and just fails instantly makes me think we've not quite got `hy -m` to where it needs to be.
