### ISSUE TITLE
Problem running hy on osx / macos 10.12.1

### ISSUE THREAD

**Issue by cpdean** [hylang/hy#1185]
Cloned the repo and installed from master, `ca6fd66606c1bf4c6a2a415cf469b1d4a36ea715`

Running interpreter fails:

```
$ hy
Traceback (most recent call last):
  File "/Users/cdean/.virtualenvs/hy/bin/hy", line 11, in <module>
    load_entry_point('hy', 'console_scripts', 'hy')()
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/cdean/dev/foss/python/hy/hy/hy/cmdline.py", line 45, in <module>
    from hy.completer import completion
  File "/Users/cdean/dev/foss/python/hy/hy/hy/completer.py", line 44, in <module>
    import pyreadline.rlmain
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Users/cdean/.virtualenvs/hy/lib/python2.7/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
```

How can I troubleshoot this?

python version:

```python --version
Python 2.7.10
```

pip freeze:

```
appdirs==1.4.0
appnope==0.1.0
args==0.1.0
astor==0.5
backports.shutil-get-terminal-size==1.0.0
clint==0.5.1
decorator==4.0.10
enum34==1.1.6
-e git+git@github.com:hylang/hy.git@ca6fd66606c1bf4c6a2a415cf469b1d4a36ea715#egg=hy
ipython==5.1.0
ipython-genutils==0.1.0
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
Pygments==2.1.3
pyreadline==2.1
rply==0.7.4
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
wcwidth==0.1.7
```

**Comment by kirbyfan64** [comment]
I'm starting to get the vibe that readline on OSX is flat-out broken (#1177).

**Comment by rcarmo** [comment]
@kirbyfan64 it is, mostly. I use `pyenv` and build my own interpreters, but "fixing" `readline` is a common enough affair.

**Comment by cpdean** [comment]
Where can I read about how to get hy working on macos 10.12.1?  I'm not familiar enough with how the dependencies are breaking and I feel like I may be maintaining my venv in the wrong way.  How does everyone else do it?

**Comment by kirbyfan64** [comment]
Wait, do you have pyreadline installed?

http://stackoverflow.com/questions/32608232/valueerror-type-v-not-supported-error-after-installing-pyreadline

**Comment by kirbyfan64** [comment]
Hy probably shouldn't even *try* to import pyreadline on Windows.

**Comment by asimjalis** [comment]
The problem is that on line 50 in `completer.py` it assumes `readline` was imported. This should add a check for `docomplete` which is `True` when `readline` is not imported.

I can submit a pull request if this change looks ok.

In https://github.com/hylang/hy/blob/master/hy/completer.py#L50

Replace:

    if sys.platform == 'darwin' and 'libedit' in readline.__doc__:

With:

    if sys.platform == 'darwin' and docomplete and 'libedit' in readline.__doc__:

**Comment by kirbyfan64** [comment]
@asimjalis https://github.com/hylang/hy/pull/1177#issuecomment-267808182

**Comment by Kodiologist** [comment]
From the comment @kirbyfan64 linked to, it looks like the bug is in `pyenv` on Mac OS not requiring GNU Readline, and thus producing a broken Python.
