### ISSUE TITLE
Require seems to have stopped working

### ISSUE THREAD

**Issue by danceasarxx** [hylang/hy#1192]
According to the docs, this is how a macro import should happen
```hy
(require [hy.contrib.multi [defn]])
```

But it rather produces this
```python
Traceback (most recent call last):
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 2662, in hy_compile
    result = compiler.compile(tree)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 432, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 628, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 488, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 315, in _branch
    results = list(results)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 488, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 444, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "<string>", line 1, in raise_empty
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ ImportError: cannot require names: ['when_not']
Compilation traceback:
File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 432, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 2056, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/compiler.py", line 1768, in compile_require
    require(module, self.module_name, assignments=assignments)
  File "/home/arewa/.pyenv/versions/barelib/lib/python3.5/site-packages/hy/macros.py", line 122, in require
    raise ImportError("cannot require names: " + repr(list(unseen)))
```

I thought it was my system until i tried it on you [online interpreter](https://try-hy.appspot.com/).

**Comment by Kodiologist** [comment]
The new `require` syntax is a feature of bleeding-edge Hy (which should be released as 0.12). try-hy uses 0.10.1.

**Comment by danceasarxx** [comment]
so how do I use import  macros?

**Comment by Kodiologist** [comment]
You can find the documentation for the latest stable release at http://hy.readthedocs.io/en/stable/ . To answer your question, in the latest stable release, just say `(require hy.contrib.multi)` and that will import every macro in `hy.contrib.multi`.

**Comment by danceasarxx** [comment]
thanks....by the way how can I help with docs

**Comment by Kodiologist** [comment]
It's great that you ask, since the documentation needs work but nobody's paying it much heed at the moment. Just fork this repo, make your changes in a new branch, and open a pull request. The `docmebro` tag ( https://github.com/hylang/hy/labels/docmebro ) shows open issues about documentation.

**Comment by danceasarxx** [comment]
ok
