### ISSUE TITLE
macroexpand doesn't like macros with named imports

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1207]
Consder

    (defmacro m [] (import [math [sqrt]]) '1)

Evaluating `(m)` works, but `(macroexpand '(m))` creates the below traceback (we have a different issue, #818, for messy tracebacks from `macroexpand`). If you do `(import math)` instead of ` (import [math [sqrt]])`, there's no error.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/macros.py", line 217, in macroexpand_1
        obj = wrap_value(m(*ntree[1:], **opts))
      File "/tmp/foo.hy", line 1, in _hy_anon_fn_1
        (defmacro m [] (import [math [sqrt]]) '1)
    ImportError: No module named '[]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/cmdline.py", line 185, in pretty_error
        return func(*args, **kw)
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/importer.py", line 79, in import_file_to_module
        eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
      File "/tmp/foo.hy", line 2, in <module>
        (print (macroexpand '(m)))
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/core/language.hy", line 323, in macroexpand
        (hy.macros.macroexpand form (HyASTCompiler name)))
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/macros.py", line 181, in macroexpand
        tree = macroexpand_1(tree, compiler)
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/macros.py", line 224, in macroexpand_1
        raise HyMacroExpansionError(tree, msg)
    hy.errors.HyMacroExpansionError: <exception str() failed>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/hy", line 11, in <module>
        load_entry_point('hy==0.12.0', 'console_scripts', 'hy')()
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/cmdline.py", line 342, in hy_main
        sys.exit(cmdline_handler("hy", sys.argv))
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/cmdline.py", line 330, in cmdline_handler
        return run_file(options.args[0])
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/cmdline.py", line 212, in run_file
        pretty_error(import_file_to_module, "__main__", filename)
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/cmdline.py", line 188, in pretty_error
        print(e, file=sys.stderr)
      File "/usr/local/lib/python3.5/dist-packages/hy-0.12.0-py3.5.egg/hy/errors.py", line 64, in __str__
        line = self.expression.start_line
    AttributeError: 'HyExpression' object has no attribute 'start_line'

**Comment by hrehfeld** [comment]
I have this case:

    (defn get-sym [] 'foo)
    
    (defmacro setnq [var]
      ;;(assert (even? (len vars)))
      `(setv ~(eval var) True))
    
Resulting in:

    hy 0.12.1+70.gad94343 using CPython(default) 3.6.0 on Linux
    => (get-sym)
    'foo'
    => (setnq 'foo)
    => foo
    True
    => (setnq (get-sym))
      File "<input>", line 1, column 1
    
      (setnq (get-sym))
      ^---------------^
    HyMacroExpansionError: b'expanding `setnq\': NameError("name \'get_sym\' is not defined",)'
    
    
    => (macroexpand-1 '(setnq (get-sym)))
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/hy/macros.py", line 215, in macroexpand_1
        obj = wrap_value(m(*ntree[1:], **opts))
      File "<eval>", line 1, in <lambda>
      File "/usr/lib/python3.6/site-packages/hy/importer.py", line 198, in hy_eval
        return eval(ast_compile(expr, "<eval>", "eval"), namespace)
      File "<eval>", line 1, in <module>
    NameError: name 'get_sym' is not defined
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/hy/cmdline.py", line 125, in runsource
        ast_callback)
      File "/usr/lib/python3.6/site-packages/hy/importer.py", line 198, in hy_eval
        return eval(ast_compile(expr, "<eval>", "eval"), namespace)
      File "<eval>", line 1, in <module>
      File "/tmp/pkgbuild-1000/hy-git/src/hy/hy/core/language.hy", line 327, in macroexpand_1
      File "/usr/lib/python3.6/site-packages/hy/macros.py", line 222, in macroexpand_1
        raise HyMacroExpansionError(tree, msg)
    hy.errors.HyMacroExpansionError: <exception str() failed>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/bin/hy", line 11, in <module>
        load_entry_point('hy==0.12.1+70.gad94343', 'console_scripts', 'hy')()
      File "/usr/lib/python3.6/site-packages/hy/cmdline.py", line 367, in hy_main
        sys.exit(cmdline_handler("hy", sys.argv))
      File "/usr/lib/python3.6/site-packages/hy/cmdline.py", line 362, in cmdline_handler
        return run_repl(spy=options.spy, output_fn=options.repl_output_fn)
      File "/usr/lib/python3.6/site-packages/hy/cmdline.py", line 257, in run_repl
        os=platform.system()
      File "/usr/lib/python3.6/code.py", line 233, in interact
        more = self.push(line)
      File "/usr/lib/python3.6/code.py", line 259, in push
        more = self.runsource(source, self.filename)
      File "/usr/lib/python3.6/site-packages/hy/cmdline.py", line 131, in runsource
        print(e, file=sys.stderr)
      File "/usr/lib/python3.6/site-packages/hy/errors.py", line 64, in __str__
        line = self.expression.start_line
    AttributeError: 'HyExpression' object has no attribute 'start_line'
    
    Process inferior-lisp exited abnormally with code 1

**Comment by Kodiologist** [comment]
I don't think that's related to this issue, although it is another example of #818.

**Comment by Kodiologist** [comment]
Tested in [`test-macroexpand-with-named-import`](https://github.com/hylang/hy/blob/eeb0be8fb0bdbd9d7d23dc908be2d24d4e475d0a/tests/native_tests/language.hy#L1308).
