### ISSUE TITLE
NameError: name 'let' is not defined

### ISSUE THREAD

**Issue by Netherdrake** [hylang/hy#1291]
```
~ % hy
hy 0.12.1+87.ga537d33 using CPython(default) 3.5.2 on Linux
=> (let [foo {}]
... (print foo))
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.5/site-packages/hy/importer.py", line 193, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'let' is not defined
=> 

```

It works fine with PyPI version:
```
~ % hy
hy 0.12.1 using CPython(default) 3.5.2 on Linux
=> (let [foo {}] (print foo))
{}
=> 
```

**Comment by Kodiologist** [comment]
This is on purpose. See #1216.

**Comment by andres-lowrie** [comment]
for any future web search traveler: Use `setv` instead of `let`

**Comment by allison-casey** [comment]
or use `hy.contrib.walk.let`

**Comment by Kodiologist** [comment]
Which is probably going to be `(require hyrule [let])` by the time the next alpha is out.

**Comment by scauligi** [comment]
and possibly full circle back to a builtin `let` if I can get my PR done in a timely manner
