### ISSUE TITLE
Error installing master branch

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1331]
I wanted to update to test the new unpacking features but there is an error in installing:

```
pip install git+https://github.com/hylang/hy.git
Collecting git+https://github.com/hylang/hy.git
  Cloning https://github.com/hylang/hy.git to /tmp/pip-w3ih6gqj-build
Requirement already satisfied: rply>=0.7.5 in ./.virtualenvs/pop-synthvenv/lib/python3.6/site-packages (from hy==0.13.0+42.g35f7dd3)
Requirement already satisfied: astor>=0.5 in ./.virtualenvs/pop-synthvenv/lib/python3.6/site-packages (from hy==0.13.0+42.g35f7dd3)
Requirement already satisfied: clint>=0.4 in ./.virtualenvs/pop-synthvenv/lib/python3.6/site-packages (from hy==0.13.0+42.g35f7dd3)
Requirement already satisfied: appdirs in ./.virtualenvs/pop-synthvenv/lib/python3.6/site-packages (from rply>=0.7.5->hy==0.13.0+42.g35f7dd3)
Requirement already satisfied: args in ./.virtualenvs/pop-synthvenv/lib/python3.6/site-packages (from clint>=0.4->hy==0.13.0+42.g35f7dd3)
Installing collected packages: hy
  Running setup.py install for hy ... error
    Complete output from command /root/.virtualenvs/pop-synthvenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-w3ih6gqj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c2z0vbgj-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/pop-synthvenv/include/site/python3.6/hy:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-w3ih6gqj-build/setup.py", line 87, in <module>
        "Topic :: Software Development :: Libraries",
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-w3ih6gqj-build/setup.py", line 30, in run
        "." + filename[:-len(".hy")])
      File "/root/.virtualenvs/pop-synthvenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/tmp/pip-w3ih6gqj-build/hy/importer.py", line 237, in load_module
        return import_file_to_module(fullname, self.path, self)
      File "/tmp/pip-w3ih6gqj-build/hy/importer.py", line 96, in import_file_to_module
        _ast = import_file_to_ast(fpath, module_name)
      File "/tmp/pip-w3ih6gqj-build/hy/importer.py", line 54, in import_file_to_ast
        return hy_compile(import_file_to_hst(fpath), module_name)
      File "/tmp/pip-w3ih6gqj-build/hy/importer.py", line 42, in import_file_to_hst
        return import_buffer_to_hst(f.read())
      File "/tmp/pip-w3ih6gqj-build/hy/importer.py", line 35, in import_buffer_to_hst
        return HyExpression([HySymbol("do")] + tokenize(buf + "\n"))
      File "/tmp/pip-w3ih6gqj-build/hy/lex/__init__.py", line 17, in tokenize
        return parser.parse(lexer.lex(buf))
      File "/root/.virtualenvs/pop-synthvenv/lib/python3.6/site-packages/rply/parser.py", line 60, in parse
        self.error_handler(lookahead)
      File "/tmp/pip-w3ih6gqj-build/hy/lex/parser.py", line 361, in error_handler
        token.source_pos.lineno, token.source_pos.colno)
    hy.lex.exceptions.LexException:   File "<stdin>", line 13, column 52
    
           (with* [(PyCallGraph :output (GraphvizOutput)))]
                                                         ^
    LexException: Ran into a RPAREN where it wasn't expected.
```

**Comment by gilch** [comment]
I think #1329 will fix this. Try pulling from that branch and see if you can install.

**Comment by ekaschalk** [comment]
It installs, but the reader/sharp macros aren't working? Says version: 0.11.0+549 and neither defsharp/defreader are defined in the repl.

**Comment by gilch** [comment]
It's `deftag` now on master.

**Comment by gilch** [comment]
They can be more than one character long now. Any symbol, really, but sometimes you have to use a space where you didn't before.

**Comment by Kodiologist** [comment]
http://hy.readthedocs.io/en/master/ is the bleeding-edge version of the documentation, for use with bleeding-edge Hy.
