### ISSUE TITLE
Why is 'apply' not defined?

### ISSUE THREAD

**Issue by ackerleytng** [hylang/hy#1361]
```
$ hy
hy 0.13.0+58.ge8ffd41 using CPython(default) 3.6.1 on Darwin
=> (defn total-purchase [price amount &optional [fees 1.05] [vat 1.1]]
...   (* price amount fees vat))
=>
=> (apply total-purchase [10 15])
Traceback (most recent call last):
  File "/Users/ackerleytng/.virtualenvs/hy/lib/python3.6/site-packages/hy/importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'apply' is not defined
=>
```

**Comment by Kodiologist** [comment]
Because it was removed in #1325.

**Comment by gilch** [comment]
You can use the new `#*` and `#**` syntax instead.

**Comment by ackerleytng** [comment]
Oops. Which file should I look at/Is there documentation for `#*`?

**Comment by ackerleytng** [comment]
Got it, thanks!
