### ISSUE TITLE
Exception in __repr__ crashes repl

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1389]
```Python
=> (defclass BadRepr[] (defn __repr__ [self] (/ 0)))
class BadRepr:

    def __repr__(self):
        return (1 / 0)
None
=> (BadRepr)
BadRepr()
Traceback (most recent call last):
  File "C:\Users\ME\workspace\hy36-gilch\Scripts\hy-script.py", line 11, in <module>
    load_entry_point('hy', 'console_scripts', 'hy')()
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 341, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 336, in cmdline_handler
    return run_repl(spy=options.spy, output_fn=options.repl_output_fn)
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 231, in run_repl
    os=platform.system()
  File "C:\Users\ME\AppData\Local\Programs\Python\Python36\lib\code.py", line 233, in interact
    more = self.push(line)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python36\lib\code.py", line 259, in push
    more = self.runsource(source, self.filename)
  File "c:\users\me\documents\github\hy\hy\cmdline.py", line 118, in runsource
    print(self.output_fn(value))
  File "<eval_body>", line 1, in __repr__
ZeroDivisionError: division by zero

(hy36-gilch) C:\Users\ME\Documents\GitHub\hy>
```
It should just report the exception like Python does, not quit the repl.

**Comment by Kodiologist** [comment]
I probably created this bug when I redid the REPL. It shouldn't be hard to fix: put a `try` around the part of the code that calls the `repl-output-fn` and display any error message in a user-friendly way.
