### ISSUE TITLE
1e1000 should not be a symbol

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1448]
Hy counts `1e308` as a floating-point number, but `2e308` as a symbol. 
```Python
=> (type 1e308)
type(1e+308)

<class 'float'>
=> (type 2e308)
type(2e308)

Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 201, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name '2e308' is not defined
```

This is inconsistent. Float literals that are too large should be `inf`, because that's how Python does it.
```Python
>>> 1.7e308
1.7e+308
>>> 1.8e308
inf
```

**Comment by Kodiologist** [comment]
Sounds like a bug in my code for checking the capitalization of `Inf`.
