### ISSUE TITLE
Ugly error message for bad `require`

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1486]
When I require a macro not existed, It throws:
```
Traceback (most recent call last):
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/importer.py", line 180, in hy_eval
    _ast, expr = hy_compile(hytree, module_name, get_expr=True)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 2213, in hy_compile
    result = compiler.compile(tree)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1731, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 819, in compile_do
    return self._compile_branch(expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 545, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 318, in _branch
    results = list(results)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 545, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1731, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 372, in checker
    return fn(self, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 873, in compile_try_expression
    name)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1002, in _compile_catch_expression
    body = self._compile_branch(expr)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 545, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 318, in _branch
    results = list(results)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 545, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1731, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 372, in checker
    return fn(self, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 858, in compile_try_expression
    body += self.compile(expr.pop(0))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 472, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "<string>", line 1, in raise_empty
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ ImportError: cannot require names: [HySymbol('let')]
Compilation traceback:
File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1731, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/compiler.py", line 1486, in compile_require
    require(module, self.module_name, assignments=assignments)
  File "/home/johnzhuang/.virtualenvs/hy/lib/python3.6/site-packages/hy/macros.py", line 106, in require
    raise ImportError("cannot require names: " + repr(list(unseen)))
```
And I can't catch the Exception using `except`

**Comment by kirbyfan64** [comment]
Well, for starters, `require` is basically `import` for macros, so `(require file)` will import any macros inside `file.hy`. You *don't* run `(require macro-name)`.

That being said, the bug here is just that the raised exception isn't being handled properly.

**Comment by Kodiologist** [comment]
I'm guessing you tried something like `(try (require foo) (except [...] ...))`. The `try` can't catch an exception raised by `require` because `require` takes effect at compile-time, not run-time.

There is a minor bug here, though, which is that the error message ("cannot require names") is raised as an `ImportError` instead of a `HyTypeError`, yielding the ugly stack trace and the message "Internal Compiler Bug 😱".

**Comment by minghu6** [comment]
You mean I should require whole file (including other macro), if I am not certain some specific macro exist?

**Comment by Kodiologist** [comment]
No. There is currently no way to conditionally require a macro.

**Comment by gilch** [comment]
Not so. You can write a macro to conditionally require macros.
```Hy
(defmacro ifreq []
  (if (dec (len (input))) `(require [bar [foo]])
      `(require [baz [foo]])))
(ifreq)
(foo)
```
Of course, the `(input)` only happens once, when the above file is compiled.

**Comment by Kodiologist** [comment]
Ah, I hadn't thought of that. Well done.

**Comment by minghu6** [comment]
I don't understand the usage of `if (dec (len (input))` @gilch

**Comment by minghu6** [comment]
And anyway, using `require` bring risks of critial error. We can't do anything except *let it crash* :(.

I am not sure it's proper that raise Exception instantly during compile-time for a bad request, if we can delay the exception until the run-time, so we can handle it?

**Comment by gilch** [comment]
It's just a stupid example not relevant to the question. You can use any condition you want. All those functions are documented. If you enter nothing, it picks one branch, something the other. I only picked that  condition because it was easy to implement and test.
