### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by srfoster** [hylang/hy#1599]
In the past, I've installed hy with

```
pip install git+https://github.com/hylang/hy.git
```

When I tried this on a new computer today, I got the error below.  Did something change?  Or am I doing something wrong?

```
pip install git+https://github.com/hylang/hy.git
Collecting git+https://github.com/hylang/hy.git
  Cloning https://github.com/hylang/hy.git to /tmp/pip-req-build-t58g4e3_
Requirement already satisfied: rply>=0.7.5 in /usr/local/lib/python3.5/dist-packages (from hy==0.14.0+127.gbb10921) (0.7.5)
Requirement already satisfied: astor in /usr/local/lib/python3.5/dist-packages (from hy==0.14.0+127.gbb10921) (0.6.2)
Requirement already satisfied: clint>=0.4 in /usr/local/lib/python3.5/dist-packages (from hy==0.14.0+127.gbb10921) (0.5.1)
Requirement already satisfied: appdirs in /usr/local/lib/python3.5/dist-packages (from rply>=0.7.5->hy==0.14.0+127.gbb10921) (1.4.3)
Requirement already satisfied: args in /usr/local/lib/python3.5/dist-packages (from clint>=0.4->hy==0.14.0+127.gbb10921) (0.1.0)
Building wheels for collected packages: hy
  Running setup.py bdist_wheel for hy ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-t58g4e3_/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-t8cs05fo --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/hy
  copying hy/models.py -> build/lib/hy
  copying hy/completer.py -> build/lib/hy
  copying hy/__main__.py -> build/lib/hy
  copying hy/macros.py -> build/lib/hy
  copying hy/__init__.py -> build/lib/hy
  copying hy/inspect.py -> build/lib/hy
  copying hy/_compat.py -> build/lib/hy
  copying hy/importer.py -> build/lib/hy
  copying hy/cmdline.py -> build/lib/hy
  copying hy/compiler.py -> build/lib/hy
  copying hy/errors.py -> build/lib/hy
  copying hy/version.py -> build/lib/hy
  creating build/lib/hy/lex
  copying hy/lex/parser.py -> build/lib/hy/lex
  copying hy/lex/exceptions.py -> build/lib/hy/lex
  copying hy/lex/lexer.py -> build/lib/hy/lex
  copying hy/lex/__init__.py -> build/lib/hy/lex
  creating build/lib/hy/core
  copying hy/core/__init__.py -> build/lib/hy/core
  creating build/lib/hy/extra
  copying hy/extra/__init__.py -> build/lib/hy/extra
  creating build/lib/hy/contrib
  copying hy/contrib/__init__.py -> build/lib/hy/contrib
  copying hy/core/macros.hy -> build/lib/hy/core
  copying hy/core/shadow.hy -> build/lib/hy/core
  copying hy/core/bootstrap.hy -> build/lib/hy/core
  copying hy/core/language.hy -> build/lib/hy/core
  copying hy/extra/anaphoric.hy -> build/lib/hy/extra
  copying hy/extra/reserved.hy -> build/lib/hy/extra
  copying hy/contrib/walk.hy -> build/lib/hy/contrib
  copying hy/contrib/loop.hy -> build/lib/hy/contrib
  copying hy/contrib/sequences.hy -> build/lib/hy/contrib
  copying hy/contrib/hy_repr.hy -> build/lib/hy/contrib
  copying hy/contrib/botsbuildbots.hy -> build/lib/hy/contrib
  copying hy/contrib/multi.hy -> build/lib/hy/contrib
  copying hy/contrib/profile.hy -> build/lib/hy/contrib
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-t58g4e3_/setup.py", line 90, in <module>
      "Topic :: Software Development :: Libraries",
    File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 238, in run
      self.run_command('install')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-t58g4e3_/setup.py", line 30, in run
      "." + filename[:-len(".hy")])
    File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
    File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 251, in load_module
      return import_file_to_module(fullname, self.path, self)
    File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 104, in import_file_to_module
      _ast = import_file_to_ast(fpath, module_name)
    File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 59, in import_file_to_ast
      return hy_compile(import_file_to_hst(fpath), module_name)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 2194, in hy_compile
      result = compiler.compile(tree)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 443, in compile
      ret = self.compile_atom(_type, tree)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
      else atom_compiler(self, atom))
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 1678, in compile_expression
      ret = self.compile_atom(fn, expression)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
      else atom_compiler(self, atom))
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 760, in compile_do
      return self._compile_branch(expression)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 528, in _compile_branch
      return _branch(self.compile(expr) for expr in exprs)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 297, in _branch
      results = list(results)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 528, in <genexpr>
      return _branch(self.compile(expr) for expr in exprs)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 443, in compile
      ret = self.compile_atom(_type, tree)
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
      else atom_compiler(self, atom))
    File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 1658, in compile_expression
      expression = macroexpand(expression, self)
    File "/tmp/pip-req-build-t58g4e3_/hy/macros.py", line 194, in macroexpand
      obj = m(compiler.module_name, *tree[1:], **opts)
    File "/tmp/pip-req-build-t58g4e3_/hy/core/bootstrap.hy", line 327, in _hy_anon_var_11
  hy.errors.HyMacroExpansionError:   File "/tmp/pip-req-build-t58g4e3_/hy/contrib/botsbuildbots.hy", line 5, column 7
  
    (defn Botsbuildbots () (Botsbuildbots))
          ^------------^
  HyMacroExpansionError: defn takes a parameter list as second argument
  
  
  
  ----------------------------------------
  Failed building wheel for hy
  Running setup.py clean for hy
Failed to build hy
Installing collected packages: hy
  Running setup.py install for hy ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-t58g4e3_/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-m2ni2zpt/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-t58g4e3_/setup.py", line 90, in <module>
        "Topic :: Software Development :: Libraries",
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-t58g4e3_/setup.py", line 30, in run
        "." + filename[:-len(".hy")])
      File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 251, in load_module
        return import_file_to_module(fullname, self.path, self)
      File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 104, in import_file_to_module
        _ast = import_file_to_ast(fpath, module_name)
      File "/tmp/pip-req-build-t58g4e3_/hy/importer.py", line 59, in import_file_to_ast
        return hy_compile(import_file_to_hst(fpath), module_name)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 2194, in hy_compile
        result = compiler.compile(tree)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 443, in compile
        ret = self.compile_atom(_type, tree)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
        else atom_compiler(self, atom))
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 1678, in compile_expression
        ret = self.compile_atom(fn, expression)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
        else atom_compiler(self, atom))
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 760, in compile_do
        return self._compile_branch(expression)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 528, in _compile_branch
        return _branch(self.compile(expr) for expr in exprs)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 297, in _branch
        results = list(results)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 528, in <genexpr>
        return _branch(self.compile(expr) for expr in exprs)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 443, in compile
        ret = self.compile_atom(_type, tree)
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 430, in compile_atom
        else atom_compiler(self, atom))
      File "/tmp/pip-req-build-t58g4e3_/hy/compiler.py", line 1658, in compile_expression
        expression = macroexpand(expression, self)
      File "/tmp/pip-req-build-t58g4e3_/hy/macros.py", line 194, in macroexpand
        obj = m(compiler.module_name, *tree[1:], **opts)
      File "/tmp/pip-req-build-t58g4e3_/hy/core/bootstrap.hy", line 327, in _hy_anon_var_11
    hy.errors.HyMacroExpansionError:   File "/tmp/pip-req-build-t58g4e3_/hy/contrib/botsbuildbots.hy", line 5, column 7
    
      (defn Botsbuildbots () (Botsbuildbots))
            ^------------^
    HyMacroExpansionError: defn takes a parameter list as second argument
    
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-t58g4e3_/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-m2ni2zpt/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-t58g4e3_/
```

**Comment by kirbyfan64** [comment]
Well, in Botsbuildbots' defense, it was a creator error...

**Comment by Kodiologist** [comment]
What's a creator error?

**Comment by kirbyfan64** [comment]
I mean that it was a misuse of `()` over `[]` in the `defn` arguments list. Creator error because the person who wrote it should've used `[]` to begin with.

**Comment by gilch** [comment]
OK that should fix it. @srfoster, can you install from master now?

**Comment by srfoster** [comment]
Yep! Thanks!
