### ISSUE TITLE
global Is not valid

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#1674]
```
(def *glob* 99)
```
Traceback (most recent call last):
  File "d:\work\hy\env\lib\site-packages\hy\importer.py", line 199, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'hyx_def' is not defined

**Comment by Kodiologist** [comment]
`def` is gone as of  #1483.
