### ISSUE TITLE
Remove internal `importlib` frames from traceback

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1693]
Python 3.x uses `_call_with_frames_removed` to remove internal frames from tracebacks.  I tried it in #1687, but couldn't get it to work; might be due to this [Python issue](https://bugs.python.org/issue23773).  
Regardless, it would be good to remove those frames somehow.

**Comment by allison-casey** [comment]
as an example:
```python
>>> import a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alliejo/dev/langs/hy/a.py", line 1
    print('hi"
              ^
SyntaxError: EOL while scanning string literal
```
```clojure
=> (import a)
Traceback (most recent call last):
  File "stdin-99c0d4eb813cb56c622500ab4696f5bbb3cb3660", line 1, in <module>
    (import a)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "/home/alliejo/dev/langs/hy/a.hy", line 1
    (print 'hi"
              ^
hy.lex.exceptions.PrematureEndOfInput: Partial string literal
```
