### ISSUE TITLE
fstring support

### ISSUE THREAD

**Issue by Wagk** [hylang/hy#1725]
[PEP 498](https://www.python.org/dev/peps/pep-0498/)
[PEP 502](https://www.python.org/dev/peps/pep-0502/)
[PEP 536](https://www.python.org/dev/peps/pep-0536/)

Python has syntax that allows for something like this:
``` python
foo = 1
f"Interpolate {foo}" # "interpolate 1"
```

Does Hy have a similar analogue? Running `(f"something")` results in the following:
```
=> (f"something")
f('something')

Traceback (most recent call last):
  File "c:\users\pangt.ads\appdata\local\programs\python\python37\lib\site-packages\hy\importer.py", line 199, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'f' is not defined
```

**Comment by Wagk** [comment]
Similarly, are [byte literal syntax](https://www.python.org/dev/peps/pep-3112/) supported?

**Comment by Wagk** [comment]
Appears to be a duplicate of #1239
