### ISSUE TITLE
hy2py hangs after macro expansion (also hy --spy)

### ISSUE THREAD

**Issue by wongjoel** [hylang/hy#1815]
The following test file executes just fine in hy, but appears to hang (20+ mins) when using hy2py, or if it is input into the hy REPL with the --spy option:
```
(defmacro/g! m [mod]
  (print "Now for a slow computation")
  (setv g!x `(% ~(** 10 10 7) ~mod))
  (print "Done computing")
  g!x)

(defn myfunc [x] (m x))

(defmain [&rest args]
  (print "Executing")
  (print "Value:" (m 3))
  (print "Value:" (myfunc 3))
  (breakpoint)
  (print "Done executing"))
```

Reproduced behaviour on master: `hy 0.17.0+78.g645d2e0 using CPython(default) 3.7.3 on Linux`

When interrupted with Ctrl+C, the following traceback is printed:
```
Traceback (most recent call last):
  File "/workspace/env/hy-dev/bin/hy2py", line 12, in <module>
    sys.exit(hy2py_main())
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/hy/cmdline.py", line 690, in hy2py_main
    print(astor.code_gen.to_source(_ast))
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 62, in to_source
    generator.visit(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 876, in visit_Module
    self.write(*node.body)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 177, in write
    visit(item)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 334, in visit_FunctionDef
    self.body(node.body)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 225, in body
    self.write(*statements)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 177, in write
    visit(item)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 487, in visit_Return
    self.conditional_write(' ', node.value)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 213, in conditional_write
    self.write(*stuff)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 177, in write
    visit(item)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 748, in visit_BinOp
    self.write(left, get_op_symbol(op, ' %s '), right)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 177, in write
    visit(item)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 693, in visit_Num
    self._handle_numeric_constant(node.n)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 675, in _handle_numeric_constant
    real = part(x.real if isinstance(x, complex) else x, imaginary=False)
  File "/workspace/env/hy-dev/lib/python3.7/site-packages/astor/code_gen.py", line 673, in part
    return repr(p) + s
KeyboardInterrupt
```

**Comment by wongjoel** [comment]
That makes sense. I didn't properly understand the difference between what hy and hy2py do. Thanks for the clarification.
