### ISSUE TITLE
Hy repl 0.17.0 from pypi doesn't work on Python 3.8.0

### ISSUE THREAD

**Issue by owainkenwayucl** [hylang/hy#1827]
I've just build Python 3.8.0 on our cluster and installing Hy from pypi with pip installs (pip3 install hy) without error, but doesn't launch properly:

```
...
Successfully built clint funcparserlib args
Installing collected packages: appdirs, rply, args, clint, funcparserlib, astor, hy
Successfully installed appdirs-1.4.3 args-0.1.0 astor-0.8.0 clint-0.5.1 funcparserlib-0.3.6 hy-0.17.0 rply-0.7.7
(hy_test) Myriad [login13] tmp :) > hy
Traceback (most recent call last):
  File "/lustre/home/uccaoke/tmp/hy_test/bin/hy", line 5, in <module>
    from hy.cmdline import hy_main
  File "/lustre/home/uccaoke/tmp/hy_test/lib/python3.8/site-packages/hy/cmdline.py", line 358, in <module>
    def koan_macro(ETname):
  File "/lustre/home/uccaoke/tmp/hy_test/lib/python3.8/site-packages/hy/macros.py", line 55, in _
    fn = rename_function(fn, name)
  File "/lustre/home/uccaoke/tmp/hy_test/lib/python3.8/site-packages/hy/_compat.py", line 69, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
TypeError: an integer is required (got type bytes)
(hy_test) Myriad [login13] tmp :( > python --version
Python 3.8.0
(hy_test) Myriad [login13] tmp :) > python3
Python 3.8.0 (default, Oct 21 2019, 13:22:29) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
(hy_test) Myriad [login13] tmp :) > pip list
Package       Version
------------- -------
appdirs       1.4.3  
args          0.1.0  
astor         0.8.0  
clint         0.5.1  
funcparserlib 0.3.6  
hy            0.17.0 
pip           19.3.1 
rply          0.7.7  
setuptools    41.4.0 
wheel         0.33.6 
```

**Comment by Kodiologist** [comment]
> If you're reporting a bug, make sure you can reproduce it with the very latest, bleeding-edge version of Hy from the `master` branch on GitHub. Bugs in stable versions of Hy are fixed on `master` before the fix makes it into a new stable release.

**Comment by owainkenwayucl** [comment]
OK, I've checked and it's fixed in master.

Apologies, closing
