### ISSUE TITLE
`lfor` can't see an imported name in `hy -c`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1879]
This one is deeply bizarre.

```
$ CODE='(import math) (print (lfor j [1] (math.sqrt 5)))' 
$ hy -c "$CODE"
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
NameError: name 'math' is not defined
$ echo "$CODE" | hy           
hy 0.18.0 using CPython(default) 3.7.5 on Linux
=> [2.23606797749979]
=> 
now exiting HyREPL...
$ echo "$CODE" > /tmp/foo.hy && hy /tmp/foo.hy 
[2.23606797749979]
```

**Comment by Kodiologist** [comment]
A simpler demonstration of the problem is `hy -c '(setv x 3) (defn f [] x) (print (f))'`.
