### ISSUE TITLE
Empty form crashes compiler

### ISSUE THREAD

**Issue by KnorrFG** [hylang/hy#1885]
An empty form will crash the compiler as shown below. One would think, that this wouldn't matter, but I accidentally left a `()` in a 300 line file and it was quite hard to catch. A normal error with a line number would be nice

```
felix@alienware:~$ hy --version
hy 0.18.0
felix@alienware:~$ echo "()" > foo.hy && hy foo.hy
Traceback (most recent call last):
  File "/home/felix/.pyenv/versions/3.8.0/bin/hy", line 8, in <module>
    sys.exit(hy_main())
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hy/compiler.py", line 433, in compile
    ret = self.compile_atom(tree)
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hy/compiler.py", line 427, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hy/compiler.py", line 1730, in compile_expression
    expr = macroexpand(expr, self.module, self)
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hy/macros.py", line 316, in macroexpand
    fn = tree[0]
  File "/home/felix/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hy/models.py", line 278, in __getitem__
    ret = super(HySequence, self).__getitem__(item)
IndexError: tuple index out of range
```

**Comment by Kodiologist** [comment]
Curious; the test I added for #1657 should've have caught this.
