### ISSUE TITLE
IndexError with invalid while

### ISSUE THREAD

**Issue by nmeum** [hylang/hy#1890]
Consider the following code:

```Hy
(while () (print "foo"))
```

The code is obviously incorrect but causes an IndexError which I believe it shouldn't:

```
Traceback (most recent call last):
  File "./test/bin/hy", line 12, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.8/code.py", line 232, in interact
    more = self.push(line)
  File "/usr/lib/python3.8/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python3.8/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.8/codeop.py", line 171, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 433, in compile
    ret = self.compile_atom(tree)
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 427, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 1730, in compile_expression
    expr = macroexpand(expr, self.module, self)
  File "/usr/lib/python3.8/site-packages/hy/macros.py", line 316, in macroexpand
    fn = tree[0]
  File "/usr/lib/python3.8/site-packages/hy/models.py", line 278, in __getitem__
    ret = super(HySequence, self).__getitem__(item)
```

**Comment by Kodiologist** [comment]
I can't reproduce this:
```
hy 0.18.0+16.g88f30c4b using CPython(default) 3.8.2 on Linux
=> (while () (print "foo"))
Traceback (most recent call last):
  File "stdin-2ebb1eab683d18c48babf970fa7f37236cd69f65", line 1, in <module>
    (while () (print "foo"))
  File "<stdin>", line 1
    (while () (print "foo"))
           ^
hy.errors.HySyntaxError: empty expressions are not allowed at top level
```

**Comment by nmeum** [comment]
Interesting I can reproduce this with `0.18.0-16-g88f30c4` (the version with which I generated the output) and release 0.18.0, both on Alpine Linux Edge. I can try to gather more information later.

**Comment by Kodiologist** [comment]
How sure are you that you really did test it with 0.18.0-16-g88f30c4? You've just been working with version relabeling.

**Comment by nmeum** [comment]
> How sure are you that you really did test it with 0.18.0-16-g88f30c4? You've just been working with version relabeling.

Yep, accidentally fucked up the test with current master due to this. Sorry!
