### ISSUE TITLE
Unable to use Python and Hylang Interop

### ISSUE THREAD

**Issue by Delanii** [hylang/hy#1893]
Using example suggested in hy documentation here:

https://docs.hylang.org/en/stable/language/interop.html#using-hy-from-python

if I have both `greetings.hy` and `test.py` in same folder, I get sizeable error Traceback:

```
Traceback (most recent call last):
  File "Z:\data\_Osobni\temp\hytest.py", line 2, in <module>
    import greetings
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "C:\Program Files\Python38\lib\site-packages\hy\importer.py", line 126, in _hy_source_to_code
    hy_tree = hy_parse(source, filename=path)
  File "C:\Program Files\Python38\lib\site-packages\hy\lex\__init__.py", line 38, in hy_parse
    tokenize(_source + "\n",
  File "C:\Program Files\Python38\lib\site-packages\hy\lex\__init__.py", line 61, in tokenize
    from hy.lex.lexer import lexer
  File "C:\Program Files\Python38\lib\site-packages\hy\lex\lexer.py", line 5, in <module>
    from rply import LexerGenerator
  File "C:\Program Files\Python38\lib\site-packages\rply\__init__.py", line 2, in <module>
    from rply.lexergenerator import LexerGenerator
  File "C:\Program Files\Python38\lib\site-packages\rply\lexergenerator.py", line 5, in <module>
    from rpython.rlib.objectmodel import we_are_translated
  File "C:\Program Files\Python38\lib\site-packages\rpython\rlib\objectmodel.py", line 14, in <module>
    from rpython.tool.sourcetools import rpython_wrapper, func_with_new_name
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "C:\Program Files\Python38\lib\site-packages\hy\importer.py", line 130, in _hy_source_to_code
    return _py_source_to_code(self, data, path, _optimize=_optimize)
  File "C:\Program Files\Python38\lib\site-packages\rpython\tool\sourcetools.py", line 211
    exec source.compile() in caller.f_globals, d
         ^
SyntaxError: invalid syntax
```

How can I resolve this error and use Hy inside python?

I have tryed to follow solutions posted here:

https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path/67692#67692

and looked here:

https://stackoverflow.com/questions/61841891/how-to-include-hy-code-into-a-separate-file-and-then-import-that-using-hy

I have also tryed to move `greetings.py` into `site-packages` folder among other modules I have installed. All of my attempts led to error posted above or to `ModuleNotFound` error.

I am using CPython v. 3.8.1 and hy v. 0.18 on Windows 10. I am pretty new to this, so I might be missing some substantial step; but SO nor doc were helpfull ...

Thank you in advance.

**Comment by Kodiologist** [comment]
The version of rpython you're using isn't Python 3-compatible. `exec` is a function in Python 3, not a statement type.

**Comment by Delanii** [comment]
That is strange. How can I fix that?
I have moved to python version 3.8 just recently.
I tryed to reinstall `rpython` with `pip` to (hopefully) get latest version, but no luck there.
Could it be that rpython is available only in 32bit? (I am on 64bit OS and 64bit python).

**Comment by Kodiologist** [comment]
I don't know, but it sounds like your Python installation is messed up. Consider just deleting everything and reinstalling.

**Comment by Delanii** [comment]
Ok, just tested on different PC, CPython 64bit v. 3.7.7, hy 0.18 Win10 64bit and works OK. Thank you for your help.

Dont know where else to add that, but for future reference (if any in that case), there are two differences among testing devices:

The one showing the issue has installed CPython 3.8.1 both 32bit and 64bit (only 64bit in PATH) and also is under user-control (I dont have admin rights), but I should have all rights in folders, in which I have had copies of `.py` and `.hy` files.

So I suspect it is somehow the double install (never had issues with that before).
