### ISSUE TITLE
Can't `hy.eval` a `require` form in Python

### ISSUE THREAD

**Issue by zcaudate** [hylang/hy#1911]
I'm getting an error when doing a `require` using the `hy.eval` functionality.

The version of python works when hy is loaded:

```
hy 0.18.0 using CPython(default) 3.7.5 on Darwin                                                                                                                                
=> (require  [hy.contrib.walk [let]])                                                                                                                                           
True
```  

but fails when doing the same thing in python.

```
$ python
Python 3.7.5 (default, Jun  8 2020, 17:36:22) 
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hy
>>> hy.eval(hy.read_str("(require  [hy.contrib.walk [let]])"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hy/compiler.py", line 2099, in hy_eval
    module.__dict__, locals)
  File "<string>", line 1, in <module>
  File "/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hy/macros.py", line 170, in require
    if _same_modules(source_module, target_module):
  File "/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hy/macros.py", line 118, in _same_modules
    target_filename = _get_filename(target_module)
  File "/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages/hy/macros.py", line 109, in _get_filename
    filename = loader.get_filename()
AttributeError: type object 'BuiltinImporter' has no attribute 'get_filename'
```

**Comment by Kodiologist** [comment]
`(hy.eval (hy.read_str "(require  [hy.contrib.walk [let]])"))` seems to work fine in Hy. The bug you found is in using `hy.eval` from Python.

**Comment by zcaudate** [comment]
I really need a workaround for it because I'm doing these calls from [jep](https://github.com/ninia/jep) and I'd really like to use the `let` macro.

**Comment by Kodiologist** [comment]
If you're targeting the JVM, wouldn't you be better off with Clojure than Hy?

**Comment by zcaudate** [comment]
I am using clojure, the project is for better interoperability with python.
