### ISSUE TITLE
Document that identifiers can't start with `^`

### ISSUE THREAD

**Issue by asemic-horizon** [hylang/hy#1915]
Instead of submitting a potentially ambiguous or incomplete narrative, I'm going to post  a console log that demonstrates the problem.

```
xheimlich@xheimlich:~$ python3 -m venv hy-repr-bug
xheimlich@xheimlich:~$ source hy-repr-bug/bin/activate
(hy-repr-bug) xheimlich@xheimlich:~$ python --version
Python 3.6.9

(hy-repr-bug) xheimlich@xheimlich:~$ cat test.hy
(defmacro ^fix-keys [fields] `(+ ["ad"] ~fields))

(hy-repr-bug) xheimlich@xheimlich:~$ pip install hy==0.17.0
Collecting hy==0.17.0
  Using cached https://files.pythonhosted.org/packages/17/67/c7d078103e2b986374be547bb7dcd2e14e398bc844277cbcd8f38dd36b6c/hy-0.17.0-py2.py3-none-any.whl
Collecting astor>=0.8 (from hy==0.17.0)
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting funcparserlib>=0.3.6 (from hy==0.17.0)
Collecting clint>=0.4 (from hy==0.17.0)
Collecting rply>=0.7.7 (from hy==0.17.0)
  Using cached https://files.pythonhosted.org/packages/e7/82/388e0845abda4bba5ba041aa32e411b3eed56f518c96c6565559e713a5ed/rply-0.7.7-py2.py3-none-any.whl
Collecting args (from clint>=0.4->hy==0.17.0)
Collecting appdirs (from rply>=0.7.7->hy==0.17.0)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Installing collected packages: astor, funcparserlib, args, clint, appdirs, rply, hy
Successfully installed appdirs-1.4.4 args-0.1.0 astor-0.8.1 clint-0.5.1 funcparserlib-0.3.6 hy-0.17.0 rply-0.7.7

(hy-repr-bug) xheimlich@xheimlich:~$ hy -i test.hy
<function hyx_Xcircumflex_accentXfix_keys at 0x7f44a0771620>
hy 0.17.0 using CPython(default) 3.6.9 on Linux
=> (^fix-keys ["2"])
['ad', '2']
=> 
now exiting HyREPL...
```
That's the expected behavior. Then:
```
(hy-repr-bug) xheimlich@xheimlich:~$ pip install hy==0.19.0
Collecting hy==0.19.0
  Using cached https://files.pythonhosted.org/packages/9d/7d/24decc923f804e7b46118ab95e380473cffe6403829569c7d2f2d9a2aad2/hy-0.19.0-py2.py3-none-any.whl
Collecting colorama (from hy==0.19.0)
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: rply>=0.7.7 in ./hy-repr-bug/lib/python3.6/site-packages (from hy==0.19.0)
Requirement already satisfied: astor>=0.8 in ./hy-repr-bug/lib/python3.6/site-packages (from hy==0.19.0)
Requirement already satisfied: funcparserlib>=0.3.6 in ./hy-repr-bug/lib/python3.6/site-packages (from hy==0.19.0)
Requirement already satisfied: appdirs in ./hy-repr-bug/lib/python3.6/site-packages (from rply>=0.7.7->hy==0.19.0)
Installing collected packages: colorama, hy
  Found existing installation: hy 0.17.0
    Uninstalling hy-0.17.0:
      Successfully uninstalled hy-0.17.0
Successfully installed colorama-0.4.3 hy-0.19.0
(hy-repr-bug) xheimlich@xheimlich:~$ hy -i test.hy
Traceback (most recent call last):
  File "(defmacro ^fix-keys [fields] `(+ ["ad"] ~fields))
-ff46b2fbd8655b569bbd82c0325f4e33cb4e367d", line 1, in <module>
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/xheimlich/hy-repr-bug/lib/python3.6/site-packages/hy/core/bootstrap.hy", line 18, in defmacro
    (. (type name) __name__))
hy.errors.HyMacroExpansionError: 
  File "(defmacro ^fix-keys [fields] `(+ ["ad"] ~fields))
", line 1
    (defmacro ^fix-keys [fields] `(+ ["ad"] ~fields))
    ^-----------------------------------------------^
expanding macro defmacro
  NameError: name 'name' is not defined


hy 0.19.0 using CPython(default) 3.6.9 on Linux
=> 
```

I didn't snip pip output in case some dependencies are being installed wrong for whatever reason, although as you can see it's a fresh environment.

**Comment by Kodiologist** [comment]
You can't begin an identifier with `^` since #1810. This is a documentation bug.
