### ISSUE TITLE
`setv` in `defclass` with odd number of arguments crashes the compiler

### ISSUE THREAD

**Issue by TatriX** [hylang/hy#1920]
The following code crashes the compiler:
```lisp
(import csv)
(defclass my-dialect [csv.Dialect]
  (setv lineterminator "\n")
  (setv delimiter = ";")
  (setv quotechar = "\"")
  (setv quoting csv.QUOTE-MINIMAL))
```

And result:

```lisp
% hy
hy 0.19.0 using CPython(default) 3.8.5 on Linux
=> (import csv)
=> (defclass my-dialect [csv.Dialect]
...   (setv lineterminator "\n")
...   (setv delimiter = ";")
...   (setv quotechar = "\"")
...   (setv quoting csv.QUOTE-MINIMAL))
Traceback (most recent call last):
  File "/usr/bin/hy", line 12, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.8/code.py", line 232, in interact
    more = self.push(line)
  File "/usr/lib/python3.8/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python3.8/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.8/codeop.py", line 176, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 438, in compile
    ret = self.compile_atom(tree)
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 432, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 1782, in compile_expression
    return Result() + build_method(
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 1642, in compile_class_expression
    e = self.compile(self._rewire_init(
  File "/usr/lib/python3.8/site-packages/hy/compiler.py", line 1674, in _rewire_init
    k, v = (decls.pop(0), decls.pop(0))
IndexError: pop from empty list
```

**Comment by TatriX** [comment]
I suppose that happened becasue I've accidentally inserted `=` character there.

**Comment by Kodiologist** [comment]
Yep. A minimal version is `(defclass C [] (setv a))`.
