### ISSUE TITLE
Exceptions in tag macros crash the compiler

### ISSUE THREAD

**Issue by allison-casey** [hylang/hy#1965]
Just ran into this. An exception raised in a tag macro will cause an internal compiler bug and crash while the same in a regular macro wont. 

```hy
(deftag a []
  (raise (ValueError)))

(defmacro b []
  (raise (ValueError)))

(b) ; => ValueError
;; (a) ; => Process Hy exited abnormally with code 1 (i'm a dumb dumb and this isn't what i mean to write :/
#a() ; => Process Hy exited abnormally with code 1 
```

**Comment by jams2** [comment]
I couldn't reproduce this - is it possible to evaluate a tag macro like that?

```
=> (deftag a [] (raise (ValueError)))
import hy


def _hy_anon_var_2():
    raise ValueError()


hy.macros.tag('a')(_hy_anon_var_2)

<function hyx_Xnumber_signXa at 0x7fd6e8218a60>

=> (a)
a()

Traceback (most recent call last):
  File "stdin-1ca0792d058b66b804e3d60434c21c58281713ee", line 1, in <module>
    (a)
NameError: name 'a' is not defined
```

But possibly related? Evaluating a tag macro with the wrong number of arguments causes the REPL to crash due to a `HyCompileError`:

```
=> (deftag foo-tag [] 'bar)
from hy import HySymbol
import hy
hy.macros.tag('foo-tag')(lambda : HySymbol('bar'))

<function hyx_Xnumber_signXfoo_tag at 0x7fe35d38e160>
=> #foo-tag 1
Traceback (most recent call last):
  File "/home/joshua/PyEnvs/hy-dev/bin/hy", line 12, in <module>
    sys.exit(hy_main())
  File "/usr/lib/python3.9/code.py", line 232, in interact
    more = self.push(line)
  File "/usr/lib/python3.9/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/usr/lib/python3.9/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.9/codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "/home/joshua/build/hy-dev/hy/compiler.py", line 434, in compile
    ret = self.compile_atom(tree)
  File "/home/joshua/build/hy-dev/hy/compiler.py", line 428, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "/home/joshua/build/hy-dev/hy/compiler.py", line 1774, in compile_expression
    return Result() + build_method(
  File "/home/joshua/build/hy-dev/hy/compiler.py", line 1678, in compile_dispatch_tag_macro
    return self.compile(tag_macroexpand(
  File "/home/joshua/build/hy-dev/hy/macros.py", line 375, in tag_macroexpand
    expr = tag_macro(tree)
TypeError: hyx_Xnumber_signXfoo_tag() takes 0 positional arguments but 1 was given


Process Hy exited abnormally with code 1
```

**Comment by allison-casey** [comment]
my bad when i wrote the minimal example, evaluating the tag macro as `#b()` will cause the error for me. I also noticed the argument crash as well and i'm gonna add a check in `deftag` to enforce the unary attribute of tags

**Comment by jams2** [comment]
Oh yeah - that not only killed the REPL, it killed the terminal process I was running it in too.

**Comment by allison-casey** [comment]
I'm no rocket scientist, but that seems.... bad? 

Pretty sure I fixed both those issues in the pr so hopefully tag macro's days off nuking terminals is behind it 😌
