### ISSUE TITLE
Incorrect errors displayed in HyREPL

### ISSUE THREAD

**Issue by scauligi** [hylang/hy#2004]
```hy
hy 0.20.0+89.g33ff26a3.dirty using CPython(default) 3.9.2 on Linux

=> (defn a [a a])
Traceback (most recent call last):
  File "/usr/lib/python3.9/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.9/codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.9/codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, True)
  File "stdin-c6000d2ccd1df263b2bd313815bfae618dc57cf3", line 1
SyntaxError: duplicate argument 'a' in function definition
None

=> ; but...

=> (defn a [/])
Traceback (most recent call last):
  File "stdin-c4590d5b379ab946ccd4a96ce4e897f3dddb0494", line 1, in <module>
    (defn a [/])
  File "<stdin>", line 1
    (defn a [/])
            ^
hy.errors.HySyntaxError: positional only delimiter '/' must have an argument

=> (defn a [a a])  ; wrong error is printed below!
Traceback (most recent call last):
  File "<stdin>", line 1
    (defn a [/])
            ^
hy.errors.HySyntaxError: positional only delimiter '/' must have an argument
```

I think the error handling in the HyREPL will need a little refactoring to catch this one. The syntax error for duplicate arguments (and possibly other errors) somehow skips our try/except handling that catches most other syntax errors and simplifies stack traces, so when it gets printed it's using stale error info.

**Comment by allison-casey** [comment]
well that's odd. glad you found this one. I wonder if this is specifically related to the new `defn` format or is reproducible with other kinds of exceptions

**Comment by scauligi** [comment]
I suspect it's unrelated to the new changes, I can try to reproduce this on a prior commit when I get the chance.
