### ISSUE TITLE
Get docs building again

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2019]
It looks like #1979 broke the documentation somehow, on Read the Docs as well as my machine. `make docs` now yields

```
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [  7%] api                                                     
Exception occurred:
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/util/inspect.py", line 689, in signature_from_ast
    args = node.args
AttributeError: 'Import' object has no attribute 'args
```

<details>
<summary>Full log and traceback</summary>

```
# Sphinx version: 3.5.3
# Python version: 3.8.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   Running Sphinx v3.5.3
#   loading intersphinx inventory from https://docs.python.org/3/objects.inv...
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 14 source files that are out of date
#   updating environment:
#   [new config]
#   14 added, 0 changed, 0 removed
#   reading sources... [  7%] api
# Loaded extensions:
#   sphinx.ext.mathjax (3.5.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.5.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.5.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (3.5.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (3.5.3) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinxcontrib.hydomain (unknown version) from /home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/hydomain.py
Traceback (most recent call last):
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/parsers.py", line 104, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 285, in run
    return super().run()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/hy_documenters.py", line 504, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 125, in parse_generated_content
    state.nested_parse(content, 0, node)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 285, in run
    return super().run()
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/directives/__init__.py", line 190, in run
    name = self.handle_signature(sig, signode)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/hydomain.py", line 412, in handle_signature
    signode += _parse_arglist(arglist, self.env)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/hydomain.py", line 91, in _parse_arglist
    sig = signature_from_str("[%s]" % arglist)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinxcontrib/hydomain.py", line 87, in signature_from_str
    return signature_from_ast(function)
  File "/home/hippo/Workspace/hyenv/lib/python3.8/site-packages/sphinx/util/inspect.py", line 689, in signature_from_ast
    args = node.args
AttributeError: 'Import' object has no attribute 'args'
```

</details>

@allison-casey Any ideas?

**Comment by scauligi** [comment]
We got https://github.com/hylang/sphinxcontrib-hydomain/pull/2 merged in, so if you pull the latest copy of that the docs build should now work.

**Comment by Kodiologist** [comment]
Yep, seems to work locally, thanks. Let's keep an eye to check that it builds again after our next merge.

**Comment by Kodiologist** [comment]
Looks good.
