### ISSUE TITLE
`hy2py` and relative require

### ISSUE THREAD

**Issue by dm9pZCAq** [hylang/hy#2204]
here is my module
```
.
├── __init__.py
├── args.hy
├── config.hy
├── log.hy
├── macros.hy
├── main.hy
├── type_helpers.hy
└── utils.hy
```

when i try to compile `hy2py args.hy` it raises:
```
hy.errors.HyMacroExpansionError:
  File "args.hy", line 10
    (require .macros *)
    ^-----------------^
expanding macro require
  TypeError: the 'package' argument is required to perform a relative import for '.macros'
```

if i remove dot
```hy
(require macros *)
```
then it works with `hy2py` but breaks running module with entry point

**Comment by Kodiologist** [comment]
Interesting. Here's a minimal example:

```
$ touch '__init__.py'
$ echo '(setv foo 1)' > macros.hy
$ echo '(require .macros *)' > args.hy
$ hy2py args.hy
Traceback (most recent call last):
  File "/usr/local/bin/hy2py", line 8, in <module>
    sys.exit(hy2py_main())
hy.errors.HyMacroExpansionError: 
  File "args.hy", line 1
    (require .macros *)
    ^-----------------^
expanding macro require
  TypeError: the 'package' argument is required to perform a relative import for '.macros'
```

The exact semantics of relative imports are always tricky, but this looks like a bug. If nothing else, the error message can be improved.

**Comment by Kodiologist** [comment]
Actually, you can provoke it with plain old `hy`, not just `hy2py`.

**Comment by dm9pZCAq** [comment]
maybe should be added option to compile whole module?

for example:
```sh
hy2py some_module/

# or also specify output directory
hy2py --out-dir some_module_compiled/ some_module/
```

**Comment by Kodiologist** [comment]
That's #2079, basically.

**Comment by Kodiologist** [comment]
The failure of my example is in fact consistent with importing in Python:

```
$ mkdir pkg
$ touch pkg/__init__.py
$ echo >pkg/py_imported.py 'print("imported")'
$ echo >pkg/py_importer.py 'from .py_imported import *'
$ python3 -m pkg.py_importer
imported
$ python3 pkg/py_importer.py
Traceback (most recent call last):
  File "/tmp/pkg/py_importer.py", line 1, in <module>
    from .py_imported import *
ImportError: attempted relative import with no known parent package
```

And in Hy:

```
$ echo >pkg/hy_imported.hy '(print "imported")'
$ echo >pkg/hy_importer.hy '(import .hy_imported *)'
$ hy -m pkg.hy_importer
imported
$ hy pkg/hy_importer.hy 
Traceback (most recent call last):
…
ImportError: attempted relative import with no known parent package
```

Change the `import` to `require` and you get basically the same behavior with a worse error message (`TypeError: the 'package' argument is required to perform a relative import for '.hy_imported'`)—unless `hy_imported` happens to have already been byte-compiled. Then it runs without complaint. That looks like a bug.

An additional wrinkle is that while it's acceptable for `hy` to fail when trying to directly run a file that uses relative `import` or `require`, given that Python does the same thing, it isn't acceptable for `hy2py`, because you can't just `hy2py -m pkg.hy_importer` to get the Python for `hy_importer`. Perhaps this is a obstacle that would be solved best by a correct implementation of #2079, which would import a tree of modules in the way Python needs for relative imports to be resolved correctly.
