### ISSUE TITLE
Compiler Bug when Formatting String

### ISSUE THREAD

**Issue by nicszerman** [hylang/hy#2280]
Latest pip install hy version.
Python 3.9.7

Error message:
```
Traceback (most recent call last):
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\Scripts\hy.exe\__main__.py", line 7, in <module>
    sys.exit(hy_main())
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ Traceback (most recent call last):
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\hy\compiler.py", line 435, in compile
    ret = self.compile_atom(tree)
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\hy\compiler.py", line 429, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\hy\compiler.py", line 1881, in compile_string
    return self._format_string(string, str(string))
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\hy\compiler.py", line 1928, in _format_string
    model, item = parse_one_thing(item)
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\hy\lex\__init__.py", line 86, in parse_one_thing
    for token in lexer.lex(src_string):
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\rply\lexer.py", line 62, in __next__
    return self.next()
  File "C:\Users\nicsz\AppData\Local\Programs\Python\Python39\lib\site-packages\rply\lexer.py", line 58, in next
    raise LexingError(None, SourcePosition(
rply.errors.LexingError: (None, SourcePosition(idx=36, lineno=1, colno=32))
```
Crashes at line:
(print f"Got {(len (get search-result-clean 'items'))}")

Does not crash if line is:
(print (len (get search-result-clean "items")))

Variables:
search-result-clean: the following dictionary (it's a parsed json object)
```
{
    "items": [
        {
            "description": "Learn about outer space, leading scientific exploration, new technology, earth science basics, & more with science videos & news ...",
            "id": "UCvJiYiBUbw4tmpRSZT2r1Hw",
            "title": "Science Channel"
        },
        {
            "description": "Making science make sense. Created by: Mitchell Moffit (@mitchellmoffit) Gregory Brown (@whalewatchmeplz) CONTACT ...",
            "id": "UCC552Sd-3nyi_tk2BudLUzA",
            "title": "AsapSCIENCE"
        }
    ]
}
```

**Comment by Kodiologist** [comment]
> If you're reporting a bug, make sure you can reproduce it with the very latest, bleeding-edge version of Hy from the `master` branch on GitHub. Bugs in stable versions of Hy are fixed on `master` before the fix makes it into a new stable release.
