### ISSUE TITLE
Weird issue when trying to check version

### ISSUE THREAD

**Issue by YSCohen** [hylang/hy#2346]
```
PS ~ > hy --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\scoop\apps\python-alpha\current\Scripts\hy.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\cmdline.py", line 370, in <module>
    @macro("koan")
     ^^^^^^^^^^^^^
  File "C:\Users\user\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 55, in _
    fn = rename_function(fn, name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 388, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
```

**Comment by Kodiologist** [comment]
Whatever exactly is going on here, I can tell you that this isn't Hy master, because the line `@macro("koan")` was deleted in #2223.

**Comment by YSCohen** [comment]
```
PS ~ > hy
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yehud\scoop\apps\python-alpha\current\Scripts\hy.exe\__main__.py", line 4, in <module>
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\__init__.py", line 14, in <module>
    hy.importer._inject_builtins()
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\importer.py", line 175, in _inject_builtins
    hy.macros.load_macros(builtins)
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 234, in load_macros
    builtin_mod = importlib.import_module(builtin_mod_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\core\result_macros.py", line 47, in <module>
    @pattern_macro("do", [many(FORM)])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 70, in dec
    install_macro(name, wrapper_maker(name), fn)
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 78, in install_macro
    fn = rename_function(fn, name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehud\scoop\apps\python-alpha\3.11.0b5\Lib\site-packages\hy\macros.py", line 366, in rename_function
    new_code = type(c)(*[getattr(c, 'co_{}'.format(a))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
```

**Comment by Kodiologist** [comment]
I can't reproduce your issue [on GitHub Actions](https://github.com/hylang/hy/actions/runs/3138632268/jobs/5098180669) with Python 3.11.0rc2 (see `tests/test_bin.py`).
