### ISSUE TITLE
Can't `match` on dotted type names

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2404]
```hy
(let [a '+]
  (match a 
    '+ 1
    _ 2))
```
expected output: 2
got:
```
Traceback (most recent call last):
  File "stdin-494d70fad1aae99772cfec1259def00daabbaec3", line 1, in <module>
    (let [a '+]
NameError: name 'quote' is not defined
```
here's the generated code:
```py
import hy
_hy_let_a_1 = hy.models.Symbol('+')
_hy_anon_var_2 = None
match _hy_let_a_1:
    case quote(hyx_Xplus_signX):
        _hy_anon_var_2 = 1
    case _:
        _hy_anon_var_2 = 2
```
manual fix is not working:
```hy
(match '+ 
   (hy.models.Symbol "+") 1 
    _ 2)
```
output:
```
Traceback (most recent call last):
  File "stdin-8930588efcee2a15eccc4f2c562960b45e187fcb", line 2
    (hy.models.Symbol "+") 1 
    ^
hy.errors.HySyntaxError: parse error for pattern macro 'match': got unexpected token: hy.models.Expression([
  hy.models.Symbol('quote'),
  hy.models.Symbol('+')]), expected: some(...)
```

for now I'm falling back to if&elif.

**Comment by Kodiologist** [comment]
The forbiddance of `quote` is not a bug: `match` restricts what is allowed in patterns, as documented. [This particular case is discussed here.](https://github.com/hylang/hy/discussions/2366)

The second form wouldn't do what you want even if it was allowed. However, the fact that it's forbidden is in fact a bug, and is probably a regression I introduced in #2382. For example, this Python works

```python
import dataclasses

@dataclasses.dataclass
class C:
    x: int
C.C = C

match C.C(1):
   case C.C(1):
        print('match')
```

but the equivalent Hy fails while compiling `match`:

```hy
(import dataclasses)

(defclass [dataclasses.dataclass] C []
  #^int x)
(setv C.C C)

(match (C.C 1)
  (C.C 1)
    (print "match"))
```
