### ISSUE TITLE
Python 3.12.6 seems to have broken something

### ISSUE THREAD

**Issue by natrys** [hylang/hy#2598]
Running `hy` on its own works and starts the repl, but running a script by passing a file argument seems to fail. Tested on my OS (void linux) python that was updated this morning, but also found a docker image that can reproduce it:

```
λ podman run --rm -it bitnami/python:3.12.6 /bin/bash
root@a649c1b214dd:/app# python -m venv venv

root@a649c1b214dd:/app# source venv/bin/activate

(venv) root@a649c1b214dd:/app# pip install git+https://github.com/hylang/hy
Collecting git+https://github.com/hylang/hy
  Cloning https://github.com/hylang/hy to /tmp/pip-req-build-5bgwh8n6
  Running command git clone --filter=blob:none --quiet https://github.com/hylang/hy /tmp/pip-req-build-5bgwh8n6
  Resolved https://github.com/hylang/hy to commit ed524c61c54ab5a466fa8519b5233b5d1afce0dc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting funcparserlib~=1.0 (from hy==0.0.0)
  Using cached funcparserlib-1.0.1-py2.py3-none-any.whl.metadata (7.1 kB)
Using cached funcparserlib-1.0.1-py2.py3-none-any.whl (17 kB)
Building wheels for collected packages: hy
  Building wheel for hy (pyproject.toml) ... done
  Created wheel for hy: filename=hy-0.0.0-py3-none-any.whl size=115106 sha256=09d5c5cdd41c4cbf074fd80197b170e9ae14cde7cc02ab3a71bde94c47157a83
  Stored in directory: /tmp/pip-ephem-wheel-cache-na5a_xk8/wheels/5f/d2/29/c1fef11f15b05514e2234c0334158a097f5b2f2bd25c9e6793
Successfully built hy
Installing collected packages: funcparserlib, hy
Successfully installed funcparserlib-1.0.1 hy-0.0.0

(venv) root@a649c1b214dd:/app# echo '(print "hello")' > test.hy

(venv) root@a649c1b214dd:/app# hy test.hy
Traceback (most recent call last):
  File "/app/venv/bin/hy", line 8, in <module>
    sys.exit(hy_main())
             ^^^^^^^^^
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
TypeError: exec() arg 1 must be a string, bytes or code object
```

**Comment by Kodiologist** [comment]
Thanks for the quick report. I can reproduce this with a freshly compiled Python 3.12.6 on Ubuntu. I'm looking into it.

**Comment by Kodiologist** [comment]
It's likely due to changes to `runpy` that we need to adapt to.
