### ISSUE TITLE
HyExpressions that look equivalent are not; very weird eval bug

### ISSUE THREAD

**Issue by cndreisbach** [hylang/hy#426]
First, here's the bug in a script:

```
$ hy
hy 0.9.12
=> (defn total-purchase [price amount &optional [fees 1.05] [vat 1.1]]
... (* price amount fees vat))
=> (total-purchase 10 15)
173.25
=> (kwapply (total-purchase 10 15) {"vat" 1.05})
165.375
=> '(kwapply (total-purchase 10 15) {"vat" 1.05})
(u'kwapply' (u'total_purchase' 10L 15L) {u'vat' 1.05})
=> (eval '(kwapply (total-purchase 10 15) {"vat" 1.05}))
165.375
```

Awesome! So far, this is what we expect.

```
=> ((fn [&rest args] `(kwapply (total-purchase ~@args) {"vat" 1.05})) 10 15)
(u'kwapply' (u'total_purchase' 10L 15L) {u'vat' 1.05})
```

This looks exactly the same as our previous quoted expression, so it should eval to the same thing, right?

```
=> (eval ((fn [&rest args] `(kwapply (total-purchase ~@args) {"vat" 1.05})) 10 15))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/clinton/Projects/hy/hy/importer.py", line 106, in hy_eval
    hytree.replace(foo)
  File "/Users/clinton/Projects/hy/hy/models/list.py", line 31, in replace
    x.replace(other)
  File "/Users/clinton/Projects/hy/hy/models/list.py", line 31, in replace
    x.replace(other)
AttributeError: 'long' object has no attribute 'replace'
```

What is going on here? Are our expressions of different types?

```
=> (type '(kwapply (total-purchase 10 15) {"vat" 1.05}))
<class 'hy.models.expression.HyExpression'>
=> (type ((fn [&rest args] `(kwapply (total-purchase ~@args) {"vat" 1.05})) 10 15))
<class 'hy.models.expression.HyExpression'>
```

Nope, they're the same. This is just weird.

I don't even know what to call this bug, but it is a tricky one. You might question the utility of what I'm trying to do or why you'd want to generate code this way. I'm trying to implement multimethods, and this is stopping me.

**Comment by kirbyfan64** [comment]
Fixed by stronger error checking in `replace`.
