### ISSUE TITLE
Trying to wrap the REPL blows up

### ISSUE THREAD

**Issue by algernon** [hylang/hy#490]
```clojure
(import [sys] [io [StringIO]])
(setv sys.stdout (StringIO))
```

results in:

    Traceback (most recent call last):
      File "<input>", line 1, in <module>
    TypeError: unicode argument expected, got 'str'
    Traceback (most recent call last):
      File "/home/algernon/.virtualenvs/hydiomatic/bin/hy", line 9, in <module>
        load_entry_point('hy==0.9.12', 'console_scripts', 'hy')()
      File "/home/algernon/.virtualenvs/hydiomatic/src/hy/hy/cmdline.py", line 295, in hy_main
        sys.exit(cmdline_handler("hy", sys.argv))
      File "/home/algernon/.virtualenvs/hydiomatic/src/hy/hy/cmdline.py", line 290, in cmdline_handler
        return run_repl(spy=options.spy)
      File "/home/algernon/.virtualenvs/hydiomatic/src/hy/hy/cmdline.py", line 211, in run_repl
        version=hy.__version__
      File "/usr/lib/python2.7/code.py", line 234, in interact
        line = self.raw_input(prompt)
      File "/usr/lib/python2.7/code.py", line 281, in raw_input
        return raw_input(prompt)
    TypeError: unicode argument expected, got 'str'

Doing the same thing in a Hy program works fine, it is just the REPL that blows up.

**Comment by algernon** [comment]
Indeed, `BytesIO` is what I needed. Thanks for the hint!
