### ISSUE TITLE
cons doesn't always promote lists to HyObjects

### ISSUE THREAD

**Issue by hooblei** [hylang/hy#568]
```
=> (setv c (cons {"a" 1} []))
from hy.core.language import cons
c = cons({u'a': 1L, }, [])
=> (type (car c))
type(c[0L])
<class 'hy.models.dict.HyDict'>
=> (get (car c) "a")
c[0L][u'a']
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/maresp/workbench/cbf/venv/lib/python2.7/site-packages/hy/models/list.py", line 43, in __getitem__
    ret = super(HyList, self).__getitem__(item)
TypeError: list indices must be integers, not unicode
=>
```

The cons is because I'm not sure how to get/construct a HyDict otherwise

**Comment by gilch** [comment]
Did #1314 fix this one?

**Comment by Kodiologist** [comment]
Honestly, your guess is as good as mine. Cons cells are a part of the language I've yet to touch.
