### ISSUE TITLE
list-comp only iterates over the last expression when it is passed a do

### ISSUE THREAD

**Issue by asmundg** [hylang/hy#588]
Only the last expression in do is interpreted in context of the list-comp:

```
=> (list-comp (do (print n) (print n)) [n [1 2]])
print(n)
[print(n) for n in [1L, 2L]]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'n' is not defined
```

Workaround (and the expected result of the above function):

```
=> (list-comp ((fn [a] (do (print a) (print a))) n) [n [1 2]])
def _hy_anon_fn_1(a):
    print(a)
    return print(a)
[_hy_anon_fn_1(n) for n in [1L, 2L]]
1
1
2
2
[None, None]
```

**Comment by gilch** [comment]
Here's a similar example:
```Hy
=> (print (list-comp (assert x) [x [1 2 3]]))
assert x
print([None for x in [1, 2, 3]])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'x' is not defined
```
Surprising behavior like this is unacceptable, but what should this even compile to?
Maybe something like this:
```Python
_hy_anon_var_1 = []
for x in [1, 2, 3]:
    assert x
    _hy_anon_var_1.append(None)
print(_hy_anon_var_1)
```
This leaks `x` into the surrounding scope, which was actually correct for Python 2.

The above won't work for a `genexpr`, which is also broken:
```Hy
=> (list (genexpr (assert x) [x [1 2 3]]))
assert x
list((None for x in [1, 2, 3]))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'x' is not defined
```
It must be lazy to work correctly. Maybe something like this:
```Python
_hy_anon_var_1 = [1, 2, 3]
def _hy_anon_fn_1():
    for x in _hy_anon_var_1:
        assert x
        yield None
list(_hy_anon_fn_1())
```
No leak this time. You can use `genexpr` to implement all the other comprehensions. This seems like an improvment over the status quo, but compiling to a function like this introduces the same problems we had with `let`.

**Comment by gilch** [comment]
Probably relevant: https://stackoverflow.com/questions/32139885/yield-in-list-comprehensions-and-generator-expressions#32139977

Basically, Python compiles generator expressions to generator function objects anyway. Therefore it won't cause problems (beyond what problems Python already has) if we do the same in Hy, as I suggested in my previous comment.

**Comment by gilch** [comment]
Here's an even simpler example.
```Python
>>> [(lambda: x)() for x in range(5)]
[0, 1, 2, 3, 4]
```
```Hy
=> (list-comp ((fn [] x)) [x (range 5)])
[(lambda : x)() for x in range(5)]
[0, 1, 2, 3, 4]
=> (list-comp ((fn [] "boo!" x)) [x (range 5)])
def _hy_anon_fn_1():
    'boo!'
    return x
[_hy_anon_fn_1() for x in range(5)]
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 198, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
  File "<eval>", line 1, in <listcomp>
  File "<eval_body>", line 1, in _hy_anon_fn_1
NameError: name 'x' is not defined
```

**Comment by gilch** [comment]
Digging this up because of the recent #1342 and #1362 which have similar problems.

I think we have a good solution. I'm proposing that generally, if there are any expressions we have to pull out, that
```Hy
(genexpr <expression> [<binding> <sequence>] <condition>)
```
Should compile to
```Python
# <sequence> statements naturally go here.
_hy_anon_var_1 = <sequence>
def _hy_anon_fn_1():
    for <binding> in _hy_anon_var_1:
        # Pull out any <condition> statements here.
        if <condition>:
            # Pull out any <expression> statements here.
            yield <expression>
_hy_anon_fn_1()
```

For a `list-comp`, change the last line to
```Python
[_hy_anon_var_2 for _hy_anon_var_2 in _hy_anon_fn_1()]
```
We shouldn't use `list(_hy_anon_fn_1())`, because `list` might be shadowed by a local.
Similarly for the `set-comp`, but use `{}` instead of `[]`.

A `dict-comp` is a little different:
```Hy
(dict-comp <key> <value> [<binding> <sequence>] <condition>)
```
```Python
# <sequence> statements.
_hy_anon_var_1 = <sequence>
def _hy_anon_fn_1():
    for <binding> in _hy_anon_var_1:
        # <condition> statements
        if <condition>:
            # Pull out any <key> or <value> statements here.
            yield <key>, <value>
{_hy_anon_var2: _hy_anon_var3 for _hy_anon_var2, _hy_anon_var3 in_hy_anon_fn_1()}
```
But it's the same basic idea.

This list-comp doesn't leak the binding into the local scope in Python2. I'm not sure if there's any point to that. It was undesired behavior due to an optimization. Generator expressions, and set- and dict-comprehensions don't have this problem even in Python2. And we won't be supporting Python2 much longer anyway.

But the leaky Python2 list-comp could instead be compiled like
```Python
# Pull out any <sequence> statements here.
_hy_anon_var_1 = <sequence>
_hy_anon_var_2 = []
for <binding> in _hy_anon_var_1:
    # Pull out any <condition> statements here.
    if <condition>:
        # Pull out any <expression> statements here.
        _hy_anon_var_2.append(<expression>)
_hy_anon_var_2
```

**Comment by gilch** [comment]
I forgot the case with multiple bindings:
```Hy
(genexpr <expression>
         [<binding1> <sequence1>
          <binding2> <sequence2>
            ...
          <bindingN> <sequenceN>])
```
But the compilation is straightforward. Add more loops:
```Python
# <sequence1> statements
_hy_anon_var_1 = <sequence1>
def _hy_anon_fn_1():
    for <binding1> in _hy_anon_var_1:
        # <sequence2> statements
        _hy_anon_var_2 = <sequence2>
        for <binding2> in _hy_anon_var_2:
             ...
            # <sequenceN> statements
            _hy_anon_var_N = <sequenceN>
            for <bindingN> in _hy_anon_var_N:
                # <expression> statements
                yield <expression>
_hy_anon_fn_1()
```
