### ISSUE TITLE
Can't perform a relative import from within __init__.hy

### ISSUE THREAD

**Issue by ghost** [hylang/hy#589]
```
% echo '(import x)' > pkg/__init__.hy
% echo '(print "hello")' > pkg/x.hy              
% python
>>> import hy, pkg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kamil/.local/lib/python2.7/site-packages/hy-0.10.0-py2.7.egg/hy/importer.py", line 176, in load_module
    self.path)
  File "/home/kamil/.local/lib/python2.7/site-packages/hy-0.10.0-py2.7.egg/hy/importer.py", line 74, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "/home/kamil/pkg/__init__.hy", line 1, in <module>
    (import x)
ImportError: No module named x
```

Same when trying to `(import pkg.x)` within `__init__.hy`

**Comment by Kodiologist** [comment]
This doesn't work in Python 3, either:

    $ echo 'import x' > pypkg/__init__.py
    $ echo 'print("hello")' > pypkg/x.py
    $ python3           
    Python 3.6.1 (default, May  1 2017, 14:17:25) 
    [GCC 6.3.0 20170406] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pypkg
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/tmp/pypkg/__init__.py", line 1, in <module>
        import x
    ModuleNotFoundError: No module named 'x'

It works in Python 2, but is it worth implementing a Python 2-specific importing feature in Hy? I'm inclined to say no.
