### ISSUE TITLE
Hy is not picking up Python Path from venv environment

### ISSUE THREAD

**Issue by stormcoder** [hylang/hy#632]
I have found that certain modules will not import in Hy but will import in python. I'm running Hy .10.0 on Python 3.4.1 x64 on Windows 7.

```
=> (import cx_Oracle)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named 'cx_Oracle'
=> (import cx-Oracle)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named 'cx_Oracle'
=> (import cx-oracle)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named 'cx_oracle'
=> (import zmq)
=> (import tornado)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: No module named 'tornado'
```

Python output:

```
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> import tornado
```

Hy Python Path:

```
hy 0.10.0
=> (import sys)
=> (. sys path)
['', 'C:\\Python34\\Scripts', 'C:\\Windows\\system32\\python34.zip', 'C:\\Python
34\\DLLs', 'C:\\Python34\\lib', 'C:\\Python34', 'C:\\Users\\mowens\\AppData\\Roa
ming\\Python\\Python34\\site-packages', 'C:\\Python34\\lib\\site-packages', 'C:\
\Python34\\lib\\site-packages\\win32', 'C:\\Python34\\lib\\site-packages\\win32\
\lib', 'C:\\Python34\\lib\\site-packages\\Pythonwin', 'C:\\Users\\mowens\\Docume
nts\\QA\\lib']
```

Python:

```
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Windows\\system32\\python34.zip', 'C:\\Python34\\DLLs', 'C:\\Python34\
\lib', 'C:\\Python34', 'C:\\Users\\mowens\\Documents\\Env\\Activation34', 'C:\\U
sers\\mowens\\Documents\\Env\\Activation34\\lib\\site-packages', 'C:\\Users\\mow
ens\\Documents\\Env\\Activation34\\lib\\site-packages\\win32', 'C:\\Users\\mowen
s\\Documents\\Env\\Activation34\\lib\\site-packages\\win32\\lib', 'C:\\Users\\mo
wens\\Documents\\QA\\lib']
```

**Comment by reillysiemens** [comment]
I just encountered this issue. Any word on where it's at? I can work around it, but it'd be nice to know if something can be done on `hy`'s end.

**Comment by paultag** [comment]
@reillysiemens Are you sure hy is installed inside your virtualenv? This issue sounds like Hy was installed with `sudo pip install` or via `apt-get install` and not working inside a virtualenv.

(Just like Python, FWIW)

**Comment by paultag** [comment]
```
(hy)[paultag@cassiel:~][⌚ 08:41 PM] ♥  python3 -c 'import sys; print(sys.path)'
['', '/home/paultag/dev/local/hy', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages/clint-0.5.1-py3.4.egg', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages/astor-0.5-py3.4.egg', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages/rply-0.7.4-py3.4.egg', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages/args-0.1.0-py3.4.egg', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages/appdirs-1.4.0-py3.4.egg', '/home/paultag/.virtualenvs/hy/lib/python3.4', '/home/paultag/.virtualenvs/hy/lib/python3.4/plat-x86_64-linux-gnu', '/home/paultag/.virtualenvs/hy/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/paultag/.virtualenvs/hy/lib/python3.4/site-packages']
(hy)[paultag@cassiel:~][⌚ 08:41 PM] ♥  /usr/bin/python3 -c 'import sys; print(sys.path)'
['', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']
```

Check `which hy`. It should be in the virtualenv, not out of it.

```
(hy)[paultag@cassiel:~][⌚ 08:41 PM] ♥  which hy
/home/paultag/.virtualenvs/hy/bin/hy
``

Just like Python:

```
(hy)[paultag@cassiel:~][⌚ 08:42 PM] ♥  which python
/home/paultag/.virtualenvs/hy/bin/python
```

**Comment by paultag** [comment]
Anyway I'm pretty sure that's the issue. If I get a few ACKs that that's the issue, I can close this out :)

:+1:

**Comment by reillysiemens** [comment]
Yeah, that was definitely the issue as mentioned above. Installing `hy` into the virtualenv fixes the problem. Here's the behavior I see:

With no system-level `hy` and `hy` instead installed in a virtualenv made with virtualenvwrapper's `mkvirtualenv` I get
```
=> (import sys)
=> sys.path
['', '/home/tucker/.virtualenvs/hy/bin', '/home/tucker/.virtualenvs/hy/lib/python3.4', '/home/tucker/.virtualenvs/hy/lib/python3.4/plat-x86_64-linux-gnu', '/home/tucker/.virtualenvs/hy/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/tucker/.virtualenvs/hy/lib/python3.4/site-packages']
```
If `hy` is installed at the system level (i.e. `sudo pip install hy`) I get
```
=> (import sys)
=> sys.path
['', '/usr/local/bin', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']
```
The second example is also true for using a system-level `hy` inside a virtualenv without `hy` installed into the virtualenv. Running `python3` in the same virtualenv gives the appropriate search path.
```
>>> import sys
>>> sys.path
['', '/home/tucker/.virtualenvs/hy2/lib/python3.4', '/home/tucker/.virtualenvs/hy2/lib/python3.4/plat-x86_64-linux-gnu', '/home/tucker/.virtualenvs/hy2/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/tucker/.virtualenvs/hy2/lib/python3.4/site-packages']
```
This leads me to believe (as @stormcoder suggested) that there might be something that can be done RE sensitivity to the current env. It might also be related to the virtualenv's utter indifference to `hy`.

**Comment by Foxboron** [comment]
Status?

**Comment by reillysiemens** [comment]
@Foxboron: Thanks for checking up on this. The behavior I mentioned above it still exactly what I'm seeing.

**Comment by Kodiologist** [comment]
Overall this seems to be more of a virtualenv pitfall than anything we should be trying to fix in Hy, so I'm going to close this issue.
