### ISSUE TITLE
`Let` creates a closure where I unable to change outer variables because of UnboundLocalError

### ISSUE THREAD

**Issue by svetlyak40wt** [hylang/hy#664]
``` lisp
(defun test []
  (setv foo true)
  (let []
       (if foo
           (setv foo false))))

(test)
```

Compiles into:

``` python
def test():
    foo = True

    def _hy_anon_fn_1():
        if foo:
            foo = False
            _hy_anon_var_1 = foo
        else:
            _hy_anon_var_1 = None
        return _hy_anon_var_1
    return _hy_anon_fn_1()
test()
```

which leads to:

```
Traceback (most recent call last):
  File "/home/art/yandex-certificator/hy/env/bin/hy", line 8, in <module>
    load_entry_point('hy==0.10.0', 'console_scripts', 'hy')()
  File "/home/art/yandex-certificator/hy/hy/cmdline.py", line 305, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/home/art/yandex-certificator/hy/hy/cmdline.py", line 293, in cmdline_handler
    return run_file(options.args[0])
  File "/home/art/yandex-certificator/hy/hy/cmdline.py", line 194, in run_file
    import_file_to_module("__main__", filename)
  File "/home/art/yandex-certificator/hy/hy/importer.py", line 74, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "minimal", line 7, in <module>
    (test)
  File "minimal", line 3, in test
    (let []
  File "minimal", line 4, in _hy_anon_fn_1
    (if foo
UnboundLocalError: local variable 'foo' referenced before assignment
```

I know why this does not work in python, but this behaviour is not expected in lisp like language.

**Comment by gilch** [comment]
We don't have to fix scoping in general just to get the `let` form working, do we? The function in a `let` form is defined once, and immediately called once. In and out.
```Python
def test():
    foo = True
    def _hy_anon_fn_1(foo=foo):
        if foo:
            foo = False
            _hy_anon_var_1 = foo
        else:
            _hy_anon_var_1 = None
        return _hy_anon_var_1, foo
    _hy_anon_var_1, foo = _hy_anon_fn_1()
    return _hy_anon_var_1
```
Isn't it feasible to generate AST like this? Here, any assigned-to nonlocal is passed in as a default argument. The updated nonlocals are returned in a tuple, and reassigned all at once. It so happens in this example, that there is only one nonlocal assinged, and it's the same as the tail return, but they needn't be:
```Python
=>(defn test2 
      (setv foo 1)
      (setv bar 2)
      (print (let []
	       (print foo)
	       (print bar)
	       (setv foo "spam")
	       (setv bar "eggs")
	       "baz")
	     )
      (print foo)
      (print bar))
def test2():
    foo = 1
    bar = 2
    def _hy_anon_fn_1(foo=foo, bar=bar):
        print(foo)
        print(bar)
        foo = "spam"
        bar = "eggs"
        return "baz", foo, bar
    _hy_anon_var_1, foo, bar = _hy_anon_fn_1()
    print(_hy_anon_var_1)
    print(foo)
    return print(bar)
=> (test2)
1
2
baz
spam
eggs
```
I think this would accomplish everything we want, even for nested `let`s.

**Comment by Foxboron** [comment]
This isn't really hard. We could just pass along `**locals()` into the function.
`def _hy_anon_fn_1(**locals()):`

**Comment by kirbyfan64** [comment]
@Foxboron But changes to `locals` [aren't guaranteed to have any effect](http://stackoverflow.com/a/8028772/2097780).

**Comment by Foxboron** [comment]
I had no had enough coffee when i thought of that :coffee:
