### ISSUE TITLE
Compiler Error when using defined macro

### ISSUE THREAD

**Issue by mcktrtl** [hylang/hy#707]
Python 3.4.2, Hy 0.10.1, Windows 10 9879

If I define the macro to accept "GET" as the verb, it works smashingly. if I define it to accept a keyword such as :get and then use a dictionary to go :get->"GET", there's an error.

    ;;;
     
    (import requests)
     
     
    (defclass Hyello []
      [[--init-- (fn [self key token]
        (setv self.key key)
        (setv self.token token)
        (setv self.endpoint
          (+ "https://api.trello.com/1/{0}?key=" key "&token=" token))
        None)]
       [execute (fn [self path method &optional [payload (dict)]]
        (.json (requests.request method (.format self.endpoint path))))]])
     
     
    (defmacro def-trello-method [methodname path verb other-verb]
      (setv http-method (get {:get "GET" :post "POST" :put "PUT" :delete "DELETE"} verb))
      ;;; (= http-method other-verb) at this point returns True
      ;;; but using http-method in the macro results in an error  while other-verb works fine
      (quasiquote (setattr Hyello ~methodname (fn [self] (self.execute ~path ~http-method)))))

      ;;; this would have worked fine instead:
      ;;; (quasiquote (setattr Hyello ~methodname (fn [self] (self.execute ~path ~other-verb)))))

This is the traceback given

    => (def-trello-method "my_orgs" "members/me/organizations" :get "GET")
    Traceback (most recent call last):
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 2208, in hy_compile
        result = compiler.compile(tree)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 420, in compile
        ret = self.compile_atom(_type, tree)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 412, in compile_atom
        ret = _compile_table[atom_type](self, atom)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 564, in compile_raw_list
        ret = self._compile_branch(entries)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 451, in _compile_branch
        return _branch(self.compile(expr) for expr in exprs)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 305, in _branch
        results = list(results)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 451, in <genexpr>
        return _branch(self.compile(expr) for expr in exprs)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 432, in compile
        raise HyCompileError(e, sys.exc_info()[2])
    hy.errors.HyCompileError: Internal Compiler Bug \U0001f631
    \u2937 TypeError: replace() takes at least 2 arguments (1 given)
    Compilation traceback:
    File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 420, in compile
        ret = self.compile_atom(_type, tree)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 412, in compile_atom
        ret = _compile_table[atom_type](self, atom)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\compiler.py", line 1723, in ; compile_expression
        expression = macroexpand(expression, self.module_name)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\macros.py", line 173, in macroexpand
        tree = macroexpand_1(tree, module_name)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\macros.py", line 205, in macroexpand_1
        obj.replace(tree)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\models\list.py", line 31, in replace
        x.replace(other)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\models\list.py", line 31, in replace
        x.replace(other)
      File "C:\Users\Daniel\Miniconda3\lib\site-packages\hy\models\list.py", line 31, in replace
        x.replace(other)

**Comment by dmarteau** [comment]
This occurs when replace is called with HyList containing bare type:

(defun getn [&optional [n 0]] ` ~n) ; here n is int , not HyInteger
(defmacro test [] `[~(getn)]) ; should resolve to: [0]

(test)
...
AttributeError: 'int' object has no attribute 'replace'
...

Note that adding wrapper for HyList in macros.py may solve the issue, i.e adding line like:
HyList: lambda l: HyList(_wrap_value(x) for x in l)

**Comment by paultag** [comment]
@hylang/core let's get a PR in place. This is the last blocker for the release

**Comment by kirbyfan64** [comment]
Fixed. Forgot which PR, but this now throws a sane error.
