### ISSUE TITLE
importing woes

### ISSUE THREAD

**Issue by algernon** [hylang/hy#774]
Recently, I stumbled into a puzzling issue:

```hy
(import [wnck]
        [adderall.dsl [*]])
≡
;=> <function ≡ at 0x7f4f19bf1de8>
```

```hy
(import [adderall.dsl [*]]
        [wnck])
≡
;=> Traceback (most recent call last):
;=>  File "<input>", line 1, in <module>
;=> NameError: name '≡' is not defined
```

If I import `adderall` first, `wnck` second, and I try to import `adderall` again, then - as expected - things still fail to work.

I didn't have time to track this down further yet. This happens with hy 0.10.1, haven't checked with master yet (that throws an exception during import, fun!).

**Comment by algernon** [comment]
Happens with 0.11 and git master too.

**Comment by algernon** [comment]
This may be related to `wnck`, because if I import pretty much any other module I could think of instead of it, then both forms work.

Mind you, `(import [adderall.dsl [*]] [wnck]) (print ≡)` works in the REPL when placed on one line. On two separate lines, it fails. That's a little bit weird too.

**Comment by algernon** [comment]
Running `hy --spy` reveals:

```
=> (import [adderall.dsl [*]] [wnck]) (print ≡)
from adderall.dsl import *
import wnck
print(hy_2ch)
<function hy_2ch at 0x7f5b23e6c1b8>
=> (import [adderall.dsl [*]] [wnck])
from adderall.dsl import *
import wnck
=> (print ≡)
print(≡)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name '≡' is not defined
```

So the reason why it works in the REPL when on the same line, is likely because whatever magic `wnck` is doing is done after the REPL is done parsing and mungling the symbol names. While when its on another line, the symbol rewriting is botched by then.

**Comment by algernon** [comment]
Tempted to close this as some `wnck` hackery with python internals that I'm just not interested in solving. A workaround exists, noone else seems to have run into this issue, and by the look of things, the fix would be a workaround too, just on the hy side, instead of in libraries that dare use funky function names.

So closing it is!
