### ISSUE TITLE
`macroexpand` fails to raise a printable macro expansion error

### ISSUE THREAD

**Issue by ewaldgrusk** [hylang/hy#818]
```
$ cat foo.hy 
(defmacro foo [x] '()) (macroexpand '(foo))
$ hy foo.hy 
Traceback (most recent call last):
  File ".../hy/macros.py", line 197, in macroexpand_1
    obj = _wrap_value(m(*ntree[1:]))
TypeError: _hy_anon_fn_1() missing 1 required positional argument: 'x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File ".../hy/macros.py", line 204, in macroexpand_1
    raise HyMacroExpansionError(tree, msg)
hy.errors.HyMacroExpansionError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File ".../hy/errors.py", line 66, in __str__
    line = self.expression.start_line
AttributeError: 'HyExpression' object has no attribute 'start_line'
```

It's tracebacks all the way down.

**Comment by ewaldgrusk** [comment]
I have looked into this:

~~~ hy
(macroexpand '(bar)) ;; macroexpand(HyExpression(([] + [HySymbol(u'bar')])))
(eval '(bar)) ;; hy_eval(HyExpression(([] + [HySymbol(u'bar')])), …)
~~~

So, `macroexpand` passes its argument _unchanged_ to `HyMacroExpansionError(…)` ([hy/macros.py#L204](https://github.com/hylang/hy/blob/920c8017337bb4999aba2589f7c10a3920793242/hy/macros.py#L204)), whereas `hy_eval` adds the expected attributes (`start_line`, etc.) before macro expansion (see this little gem: [hy/importer.py#L105](https://github.com/hylang/hy/blob/920c8017337bb4999aba2589f7c10a3920793242/hy/importer.py#L105)).

Thus:
~~~
$ cat bar.hy
(defmacro bar [x] '())
(eval '(bar))
$ hy bar.hy 
  File "bar.hy", line 0, column 0

HyMacroExpansionError: expanding `bar': TypeError("_hy_anon_fn_1() missing 1 required positional argument: 'x'",)
~~~

**Comment by Kodiologist** [comment]
The problem seems to have been resolved:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/foo.hy", line 1, in <module>
    (defmacro foo [x] '()) (macroexpand '(foo))
  File "/usr/local/lib/python3.7/dist-packages/hy/core/language.hy", line 252, in macroexpand
    (hy.macros.macroexpand form module (HyASTCompiler module)))
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
hy.errors.HyMacroExpansionError: expanding macro foo
  TypeError: foo() missing 1 required positional argument: 'x'
```
