### ISSUE TITLE
Keyword argument missing the value is reported incorrectly

### ISSUE THREAD

**Issue by algernon** [hylang/hy#821]
```
(foo :a)
```

Gives me a stack trace like the following:

```
Traceback (most recent call last):
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 2279, in hy_compile
    result = compiler.compile(tree)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 313, in _branch
    results = list(results)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 440, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/_compat.py", line 66, in raise_empty
    raise t(*args)
HyCompileError: Internal Compiler Bug 😱
⤷ UnicodeEncodeError: 'ascii' codec can't encode character u'\ufdd0' in position 0: ordinal not in range(128)
Compilation traceback:
File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 1817, in compile_expression
    with_kwargs)
  File "/home/algernon/.virtualenvs/hy-issue/local/lib/python2.7/site-packages/hy/compiler.py", line 462, in _compile_collect
    raise HyCompileError(msg.format(kw=str(expr)))
```

The real error is not reported anywhere, but visiting line 462 in compiler.hy reveals that it should be reporting `Keyword argument :a needs a value`. The `\ufdd0` should probably be stripped.

I'll submit a patch in a bit.

**Comment by algernon** [comment]
Fixed on master.
