### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#916]
I Just Use them like that
```
(import [os])
(import [util [concat select repeat_fn]])
(defn str2tuple [s]
	(tuple s))

;;;;;;;;;;;;;;;;;;;;;;;
;
; Match funtion group


(defn match_fn [t fun]
	(cond [(fun (car t)) 
			(, (, True (, (car t)) )
				(cdr t))]
		  [True (, (, False (,)) t)]))

;fn 为lamba函数
; match any
(defn match_any [t] 
	(match_fn t 
	(fn [x] True )))
; match digit
(defn match_digit [t] 
	(match_fn t 
	(fn [x] (in  x "0123456789"))))

(defn match_alpha [t] 
	(match_fn t 
	(fn [x] (in  x "abcdefghijklmnopqrszuvwxyz"))))


(defn match_plus  [t]
	(match_fn t (fn [x] (= x "+"))))

(defn match_minus  [t]
	(match_fn t (fn [x] (= x "-"))))




(defn match_space [t]
	(match_fn t (fn [x] (= x " "))))
(defn match_tab [t]
	(match_fn t (fn [x] (= x "\t"))))


(defn tuple2str [x]
	(.join "" x))


;;;;;;;;;;;;;

(def phone_match
	(concat match_plus 
		(repeat_fn match_digit :min 2 :max 2)
		match_minus
		(repeat_fn match_digit :min 3 :max 3)
		match_minus
		(repeat_fn match_digit :min 8)))

(defn match_q  [t]
	(match_fn t (fn [x] (= x "\""))))

(defn match_quote2  [t]
	(match_fn t (fn [x] (= x "\""))))



(defn match_sigle_quote  [t]
	(match_fn t (fn [x] (= x "\'"))))

(defn match_string
  (concat match_q (repeat_fn match_any :min 1) match_q))
		
```
The rest code code just see `https://github.com/acekingke/regular-expression-in-hy`
D:\work\wz_todo\flask\Scripts\python.exe D:/work/tmp/regs/test.py
Traceback (most recent call last):
  File "D:/work/tmp/regs/test.py", line 3, in <module>
    import lex_parse
  File "D:\work\tmp\regs\lex_parse.py", line 3, in <module>
    import lex
  File "D:\work\wz_todo\flask\lib\site-packages\hy\importer.py", line 180, in load_module
    self.path)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "D:\work\tmp\regs/lex.hy", line 2, in <module>
    (import [reg [*]])
  File "D:\work\wz_todo\flask\lib\site-packages\hy\importer.py", line 180, in load_module
    self.path)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\importer.py", line 75, in import_file_to_module
    _ast = import_file_to_ast(fpath, module_name)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\importer.py", line 67, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 2279, in hy_compile
    result = compiler.compile(tree)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 313, in _branch
    results = list(results)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1781, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 363, in checker
    return fn(self, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1835, in compile_def_expression
    expression.start_column)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1845, in _compile_assign
    result = self.compile(result)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1781, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 363, in checker
    return fn(self, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1998, in compile_function_def
    body = self._compile_branch(expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 313, in _branch
    results = list(results)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 440, in compile
    raise_empty(HyCompileError, e, sys.exc_info()[2])
  File "D:\work\wz_todo\flask\lib\site-packages\hy\_compat.py", line 66, in raise_empty
    raise t(*args)
hy.errors.HyCompileError: Internal Compiler Bug 😱
⤷ TypeError: Can't assign / delete a <class '_ast.Call'> object
Compilation traceback:
File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1781, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 363, in checker
    return fn(self, expression)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1835, in compile_def_expression
    expression.start_column)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 1853, in _compile_assign
    st_name = self._storeize(ld_name)
  File "D:\work\wz_todo\flask\lib\site-packages\hy\compiler.py", line 588, in _storeize
    raise TypeError("Can't assign / delete a %s object" % type(name))

Process finished with exit code 1

**Comment by acekingke** [comment]
match_string cause the error

**Comment by acekingke** [comment]
Sorry， I make error.
