### ISSUE TITLE
Add other Python implementations (like IronPython and Jython) to tox or docs

### ISSUE THREAD

**Issue by gilch** [hylang/hy#934]
There are other implementations of Python that we're not testing with Hy. We should add them to our testing if possible.

If Hy is fundamentally incompatible with a given implementation, we should say so in our docs. I searched Hy's docs for "IronPython", "Jython", "Cython", "ShedSkin", and "Pyjamas" but found nothing.

**Comment by kirbyfan64** [comment]
I *seriously* doubt that eithee Shedskin or Cython would work: the former is very, very restrictive; and the latter, I believe, uses a custom parser.

**Comment by zackmdavis** [comment]
I was not able to install Hy with Jython 2.7.0 due a problem installing our `clint` dependency (looks likely to be [issue no. 2158](http://bugs.jython.org/issue2158), the fix for which didn't make the release):
```
(jirtualenv)zmd@ExpectedReturn:~/Code/Misc/Jython_Sandbox/jirtualenv$ pip install hy
Collecting hy
  Using cached hy-0.11.0.tar.gz
Collecting rply>=0.7.0 (from hy)
  Using cached rply-0.7.4-py2.py3-none-any.whl
Collecting astor>=0.5 (from hy)
  Using cached astor-0.5-py2.py3-none-any.whl
Collecting clint>=0.4 (from hy)
  Using cached clint-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-R_NesT/clint/setup.py", line 12, in <module>
        import clint
      File "clint/__init__.py", line 21, in <module>
        from .arguments import *
    ImportError: No module named arguments
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-R_NesT/clint
```

**Comment by gilch** [comment]
I also wonder about mobile Python implementations. I'm aware of SL4A and Kivy for Android. I think someone mentioned getting Hy working on Android over IRC, but I don't know which one. I'm not familiar with Python on iOS, but that might also be worth looking into.

**Comment by Foxboron** [comment]
@gilch 
http://kivy.org/planet/2014/10/hy-lisp-and%C2%A0kivy/

**Comment by paultopia** [comment]
Newbie here poking around looking for ways to get involved.  

Re mobile, there is a python implementation for iOS, actually a few, but the most popular is a closed-source paid implementation called [pythonista](http://omz-software.com/pythonista/).  It's a little restricted due to apple sandboxing---only supports 2.7, currently no way I know of to get many modules in (anything that depends on C for example) unless the guy who writes it packages it in the core "app" in an update (for example, I haven't been able to get sci-kit learn in). But there are a variety of hacks to get modules written in pure Python in.  It's all very samizdat, lots of scripts to download other scripts off github and the like, because Apple has Feelings about sideloading code.  

I may try and muck around a bit to see if I can get hy to install in a few days, will report back.

**Comment by paultopia** [comment]
Ok, I've done a little experimenting.  I can get hy installed via the latest (2.0) version of pythonista on ios, but only after a bit of rigmarole.  I can also get a repl.  But I haven't managed yet to get it to execute anything else, I suspect simply because the way I've hacked it together it needs manual imports of basically everything.  

Steps so far:
1.  Manually install stash (a commandline clone): https://github.com/ywangd/stash
2.  From stash command line, manually install dependencies in the following order via pip: 1) appdirs, 2) the listed dependencies in setup.py (astor, clint, rply)
3.  Close stash command line (trying the below without doing this first led to a crash, I suspect because of memory)
4.  Switch to pythonista console (repl).  Then, in console:

    >>> import hy
    >>> import hy.cmdline
    >>> hy.cmdline.hy_main()
    hy 0.11.1 using CPython(default) 2.7.5 on Darwin
    => 

And we have a hy repl!  Unfortunately, trying to use it blows up ugly.  Viz.: (sorry for lousy formatting, I'm pasting this in straight from ipad)

Maybe I'll try importing everything individually...

=> (print "hello hy!")
    Traceback (most recent call last):
      File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/compiler.py", line 2304, in hy_compile
        compiler = HyASTCompiler(module_name)
      File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/compiler.py", line 378, in __init__
        load_stdlib()
      File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/compiler.py", line 73, in load_stdlib
        mod = importlib.import_module(module)
      File "/var/mobile/Containers/Bundle/Application/575025AB-2EF8-4348-BA3E-A7FBA91E5011/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/importlib/__init__.py", line 38, in import_module
        __import__(name)
      File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/importer.py", line 180, in load_module
    self.path)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/importer.py", line 75, in import_file_to_module
    _ast = import_file_to_ast(fpath, module_name)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/hy/importer.py", line 67, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 2305, in hy_compile
    result = compiler.compile(tree)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 313, in _branch
    results = list(results)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/private/var/mobile/Containers/Shared/AppGroup/3CA811DC-91BC-4964-9CFE-81FFABD1596F/Documents/site-packages/hy/compiler.py", line 442, in compile
    raise HyCompileError(Exception("Unknown type: `%s'" % _type))
HyCompileError: Internal Compiler Bug 😱
⤷ Exception: Unknown type: `<class 'hy.models.expression.HyExpression'>'
Compilation traceback:
No traceback available. 😟
=>

**Comment by zackmdavis** [comment]
works on Android using [Termux](https://termux.com/)

![hy_on_android](https://cloud.githubusercontent.com/assets/1076988/15063809/0efa7322-1302-11e6-9026-8d63be9333a0.png)

**Comment by Kodiologist** [comment]
RPython may have worked at one point (#29) but probably doesn't now (#780). At any rate, we can't really say we support an implementation that we're not testing on, so for the time being, we support CPython, PyPy, and nothing else.

**Comment by Kodiologist** [comment]
Most interesting to me personally would be support for [Pyodide](https://pyodide.org), a WebAssembly-based Python, so you could run Hy in a web browser without having to go through JavaScript, as with [Brython](https://brython.info/).

**Comment by Kodiologist** [comment]
Pyodide is in as of #2388.

**Comment by Kodiologist** [comment]
[Mojo](https://github.com/modularml/mojo) is a more viable target now that it's free software, but it would take a little investigation to see just how viable. I'm not sure how much of Python it supports yet.

**Comment by armoha** [comment]
Since [GraalPy](https://graalpy.org/) finally supports `ast` module which is identical to CPython (tested for Python 3.12), I guess it wouldn't be hard to support it.

+EDIT: Tests passed locally for GraalPy on Windows : https://gist.github.com/armoha/cf13678e46d042c1bd7bab537e83e5fb
```py
> uv run -p graalpy python
Python 3.12.8 (Wed Jan 07 14:49:54 PST 2026)
[Graal, Oracle GraalVM, Java 25.0.2 (amd64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> print([name for name, obj in vars(ast).items() if callable(obj)])
['AST', 'mod', 'Module', 'Interactive', 'Expression', 'FunctionType', 'stmt', 'FunctionDef', 'AsyncFunctionDef',
 'ClassDef', 'Return', 'Delete', 'Assign', 'TypeAlias', 'AugAssign', 'AnnAssign', 'For', 'AsyncFor', 'While',
 'If', 'With', 'AsyncWith', 'Match', 'Raise', 'Try', 'TryStar', 'Assert', 'Import', 'ImportFrom', 'Global',
 'Nonlocal', 'Expr', 'Pass', 'Break', 'Continue', 'expr', 'BoolOp', 'NamedExpr', 'BinOp', 'UnaryOp', 'Lambda',
 'IfExp', 'Dict', 'Set', 'ListComp', 'SetComp', 'DictComp', 'GeneratorExp', 'Await', 'Yield', 'YieldFrom',
 'Compare', 'Call', 'FormattedValue', 'JoinedStr', 'Constant', 'Attribute', 'Subscript', 'Starred', 'Name',
 'List', 'Tuple', 'Slice', 'expr_context', 'Load', 'Store', 'Del', 'boolop', 'And', 'Or', 'operator', 'Add',
 'Sub', 'Mult', 'MatMult', 'Div', 'Mod', 'Pow', 'LShift', 'RShift', 'BitOr', 'BitXor', 'BitAnd', 'FloorDiv',
 'unaryop', 'Invert', 'Not', 'UAdd', 'USub', 'cmpop', 'Eq', 'NotEq', 'Lt', 'LtE', 'Gt', 'GtE', 'Is', 'IsNot',
 'In', 'NotIn', 'comprehension', 'excepthandler', 'ExceptHandler', 'arguments', 'arg', 'keyword', 'alias',
 'withitem', 'match_case', 'pattern', 'MatchValue', 'MatchSingleton', 'MatchSequence', 'MatchMapping',
 'MatchClass', 'MatchStar', 'MatchAs', 'MatchOr', 'type_ignore', 'TypeIgnore', 'type_param', 'TypeVar',
 'ParamSpec', 'TypeVarTuple', 'contextmanager', 'nullcontext', 'IntEnum', 'auto', '_simple_enum', 'parse',
 'literal_eval', 'dump', 'copy_location', 'fix_missing_locations', 'increment_lineno', 'iter_fields',
 'iter_child_nodes', 'get_docstring', '_splitlines_no_ff', '_pad_whitespace', 'get_source_segment', 'walk',
 'NodeVisitor', 'NodeTransformer', '_n_getter', '_n_setter', '_s_getter', '_s_setter', '_ABC', '_new',
 '_ast_Ellipsis', 'slice', 'Index', 'ExtSlice', '_dims_getter', '_dims_setter', 'Suite', 'AugLoad', 'AugStore',
 'Param', '_Precedence', '_Unparser', 'unparse', '__getattr__', 'main']
>>> print(ast.__file__)
C:\Users\[USER_NAME]\AppData\Roaming\uv\python\graalpy-3.12.0-windows-x86_64-none\Lib\ast.py
>>> tree = ast.parse("x = 1", type_comments=True)
>>> print(tree.type_ignores)
[]
>>> print(ast.unparse(tree))
x = 1
```
