### ISSUE TITLE
Class example in documentaion fails?

### ISSUE THREAD

**Issue by tikiking1** [hylang/hy#940]
```hy
(defclass FooBar [object]
  "Yet Another Example Class"

  (defn --init-- [self x]
    (setv self.x x)
    None)

  (defn get-x [self]
    "Return our copy of x"
    self.x))
```

```sh
$ hy2py test.hy
Traceback (most recent call last):
  File "/usr/bin/hy2py", line 9, in <module>
    load_entry_point('hy==0.11.0', 'console_scripts', 'hy2py')()
  File "/usr/lib/python2.7/site-packages/hy/cmdline.py", line 408, in hy2py_main
    _ast = import_file_to_ast(options.args[0], module_name)
  File "/usr/lib/python2.7/site-packages/hy/importer.py", line 67, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 2279, in hy_compile
    result = compiler.compile(tree)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 596, in compile_raw_list
    ret = self._compile_branch(entries)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 483, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 313, in _branch
    results = list(results)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 483, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 428, in compile
    ret = self.compile_atom(_type, tree)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 1781, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 420, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 363, in checker
    return fn(self, expression)
  File "/usr/lib/python2.7/site-packages/hy/compiler.py", line 2082, in compile_class_expression
    "Wrong number of argument in defclass attribute.")
hy.errors.HyTypeError:   File "None", line 1, column 1

HyTypeError: Wrong number of argument in defclass attribute.
```

**Comment by gilch** [comment]
I thought we unit tested this? I suspect that you're using an older version of Hy that had a different syntax for `defclass`. Try getting the current version of Hy from github if you haven't already. It should work.

**Comment by tikiking1** [comment]
I'm on version 0.11.0, the latest from `sudo pip install hy`.

**Comment by kirbyfan64** [comment]
@gilch is right. Try grabbing Hy from master or using the [docs for 0.11](http://docs.hylang.org/en/stable/).

**Comment by tikiking1** [comment]
Oh, sorry, I'm more used to a stable-master unstable-develop branch, rather than unstable-master stable-stable branch. My bad.
