### ISSUE TITLE
Missing from docs: how to import anaphoric macros/xi

### ISSUE THREAD

**Issue by endrebak** [hylang/hy#965]
```
$ hy -v
hy 0.11.0
hy
=> (def add-10 (xi + 10 x1))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'xi' is not defined
=> (import hy.contrib)
=> (def add-10 (hy.contrib.xi + 10 x1))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'xi'
=> (import [hy.contrib [xi]])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name xi
```

I `python setup.py install`ed the github (develop?) version yesterday, so I should be using the latest version. Would that show in the `hy -v` output? 

Anyways, how do I import `xi`? (, and perhaps how to import it should be included in the docs in some way...)

**Comment by kirbyfan64** [comment]
Try:

```
ryan@DevPC-LX:~$ hy
hy 0.11.0 using CPython(default) 2.7.6 on Linux
=> (require hy.contrib.anaphoric)
=> (def add-10 (xi + 10 x1))
=> (add-10 2)
12L
=> 
ryan@DevPC-LX:~$ 
```

**Comment by endrebak** [comment]
Thanks.

```
=> (import inspect)
=> (inspect.getmembers hy.contrib)
```

returned too much stuff for me to parse...
