### ISSUE TITLE
Can not open hy twice from virtualenv in OSX

### ISSUE THREAD

**Issue by wuxianliang** [hylang/hy#981]
Dear friends:
When I  virtualenv a new env and install hy correctly, I can call hy in repl to open hy. But once I deactivate the env then activate the second time, I can not open hy.

```shell
Traceback (most recent call last):
  File "/Users/wxl/abcd/bin/hy", line 7, in <module>
    from hy.cmdline import hy_main
  File "/Users/wxl/abcd/lib/python2.7/site-packages/hy/cmdline.py", line 44, in <module>
    from hy.completer import completion
  File "/Users/wxl/abcd/lib/python2.7/site-packages/hy/completer.py", line 50, in <module>
    if sys.platform == 'darwin' and 'libedit' in readline.__doc__:
NameError: name 'readline' is not defined
``` 
Why? That is too wired.

**Comment by wuxianliang** [comment]
I pip install --upgrade readline in root and virtualenv a new env, then hy works well.
