### ISSUE TITLE
Can't use apply when trying the interop example in the docs

### ISSUE THREAD

**Issue by anthoq88** [hylang/hy#988]
Hello,

I'm trying the interop examples in the docs:
http://docs.hylang.org/en/latest/tutorial.html#hy-python-interop

However, when I try the line `(apply (. greetings greet) ["Foo"] {:title "Lord"})` I get the error traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 11, in <module>
    sys.exit(hy_main())
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "package.hy", line 24, in <module>
    (apply (. greetings greet) ["Foo"] {:title "Lord"})
TypeError: greet() missing 1 required positional argument: 'name'
```

My version of hy is `0.11.0`

**Comment by algernon** [comment]
The syntax was improved recently, the hy 0.11.0 does not support `{:title "Lord"}` yet. Use `{"title" "Lord"}` instead.

The docs for the last released version of Hy are at http://docs.hylang.org/en/stable/

**Comment by anthoq88** [comment]
oh that makes sense.
Thanks

**Comment by anthoq88** [comment]
Actually, just tried it with the string as the key word.
Still the same issue:

```
Greetings, Sir Foo
Greetings, Darth Foo
Traceback (most recent call last):
  File "/usr/local/bin/hy", line 11, in <module>
    sys.exit(hy_main())
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 347, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 335, in cmdline_handler
    return run_file(options.args[0])
  File "/usr/local/lib/python3.5/site-packages/hy/cmdline.py", line 210, in run_file
    import_file_to_module("__main__", filename)
  File "/usr/local/lib/python3.5/site-packages/hy/importer.py", line 78, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "./package.hy", line 24, in <module>
    (apply (. greetings greet) ["Foo"] {"title" "Lord"})
TypeError: greet() missing 1 required positional argument: 'name'
```

**Comment by anthoq88** [comment]
Seems to be working on the latest release when I build from source - so I guess I'll close this.
